dimitri/pgcopydb

src/bin/pgcopydb/defaults.h
src/bin/pgcopydb/parsing.c
src/bin/pgcopydb/parsing.h

Percent-escape Postgres URI parameters.

---

Makefile
tests/unit/Dockerfile
tests/unit/Makefile
tests/unit/README.md
tests/unit/copydb.sh
tests/unit/docker-compose.yml
tests/unit/expected/1-exclusion-constraints.out
tests/unit/setup/1-exclusion-constraints.sql
tests/unit/setup/setup.sql
tests/unit/sql/1-exclusion-constraints.sql

At the moment it's quite a simple test suite, and only covers the exclusion
constraint issue #22. As more specific issues are opened, we can add to this
regression test suite.

Implement Unit/Regression testing suite.

---

docs/conf.py
docs/intro.rst
docs/ref/manual.rst
docs/ref/pgcopydb.rst
docs/ref/pgcopydb_clone.rst
docs/ref/pgcopydb_copy.rst
docs/ref/pgcopydb_stream.rst
src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/cli_common.h
src/bin/pgcopydb/cli_copy.c
src/bin/pgcopydb/cli_root.c
src/bin/pgcopydb/cli_root.h
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
tests/filtering/copydb.sh
tests/pagila/copydb.sh
tests/unit/copydb.sh

```
pgcopydb
clone    Clone an entire database from source to target
fork     Clone an entire database from source to target
follow   Replay changes from the source database to the target database
copy-db  Copy an entire database from source to target
```
Fixes #51

Review the pgcopydb commands.

---

docs/conf.py
docs/ref/manual.rst
docs/ref/pgcopydb.rst
docs/ref/pgcopydb_create.rst
src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/cli_create.c
src/bin/pgcopydb/cli_dump.c
src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/cli_root.c
src/bin/pgcopydb/cli_root.h
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
tests/pagila-multi-steps/copydb.sh

Implement pgcopydb create snapshot.

---

.github/workflows/run-tests.yml
docs/ref/pgcopydb_clone.rst
src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/cli_create.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/stream.c
src/bin/pgcopydb/stream.h
tests/cdc/copydb.sh
tests/follow/Dockerfile
tests/follow/Dockerfile.pg
tests/follow/Makefile
tests/follow/README.md
tests/follow/copydb.sh
tests/follow/ddl.sql
tests/follow/dml.sql
tests/follow/docker-compose.yml

The command starts two sub-processes that concurrently pre-fetch changes from the source
database and catch-up the target database by applying the SQL changes there.

Implement pgcopydb follow.

---

src/bin/pgcopydb/schema.c

Fix NULL columns processing when listing schema dependencies.

---

src/bin/pgcopydb/cli_clone_follow.c

This allows to stop processing in case we failed to do the Change Data
Capture setup, which involves creating a replication slot with the logical
decoding plugin wal2json. When that plugin is not available on the source
database, it's best to exit early with a clear error message.
Without this change pgcopydb clone --follow would implement the full base
copy fo the database and only then exit with an error because the follow
subprocess failed early.

When pgcopydb clone --follow is used, setup before forking subprocesses.

---

docs/ref/pgcopydb_clone.rst
docs/ref/pgcopydb_copy.rst
docs/ref/pgcopydb_dump.rst
docs/ref/pgcopydb_follow.rst
docs/ref/pgcopydb_stream.rst
src/bin/pgcopydb/cli_sentinel.c

Add documentation for the sentinel table, and add an --json option to the command pgcopydb stream sentinel get.
Also document that pg_dumpall --roles-only needs superuser privileges.

Improve pgcopydb follow docs, and some more.

---

docs/ref/pgcopydb_copy.rst
docs/ref/pgcopydb_dump.rst

Fix docs for pgcopydb dump schema --target etc.

---

src/bin/pgcopydb/stream.c

There is a case when we reach the endpos at startup (or restart), and we have a JSON file around that was not transformed yet: the current LSN is not past this file yet, and the previous time when streaming we didn't reach to the endpos yet.
Now we need to transform that JSON file into SQL, even though we don't have an open file pointer to call fclose() on.

Make sure to transform JSON files in all cases.

---

src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/table-data.c

When a connection exception happens we know it's a transient error and it's worth retrying. In scenarios with thousands of tables to COPY, being able to just retry internally is a big help.

Implement a retry strategy in case of Connection Exception.

---

src/bin/pgcopydb/ld_transform.c

The "switch" messages don't have an XID field, so refrain from validating the current transaction's XID when parsing WAL switch messages.

Fix parsing a JSON switch ("X") message.

---

src/bin/pgcopydb/pgcmd.c

The ACL and COMMENT entries that pgcopydb is interested into both have no namespace attached to them, so we expect a " - " at this position. We could still have to parse entries with a namespace, so we might as well refrain from issueing WARN messages when the namespace isn't "-".
Fixes #123.

Fix parsing ACL and COMMENT archive entries from pg_dump/pg_restore.

---

src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_transform.c

There was a couple bugs:
1. The XID in the metadata parts of the message is now a JSON string rather than a JSON number, even though the XID in the wal2json message still is a JSON number. We had to adjust to both cases, because we use the same metadata parsing code in both situations.
2. Now that transactions may contain SWITCH WAL and KEEPALIVE messages, we need to issue BEGIN lazily, rather than eagerly. That said, a LogicalTransaction struct does not contain BEGIN and COMMIT messages separately, it's part of the transaction metadata.
Adjust the code to actually work with that design.

Fix previous commit / PR.

---

src/bin/pgcopydb/pgsql.c

Blind fix attempt for a reported segfault.

---

src/bin/pgcopydb/schema.c

New: Included data copy for unlogged tables during offline migration
Fix:Fix for [exclude-index] sql query

Included data copy for unlogged tables, fix for [exclude-index] sql query

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/cli_common.h
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/ld_replay.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h

this fixes https://github.com/dimitri/pgcopydb/issues/192

Avoid using stdin/stdout/stderr as variable names

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_stream.h

Make it easier to follow what happens in bare clone operations and what happens in clone-and-follow operations.

Refactor our clone --follow implementation.

---

src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c

The KEEPALIVE and SWITCH WAL messages could be part of a transaction (typically one that spans multiple WAL files), but also can be found independently, between transactions.
Our previous internal representation insisted that every message be put in the context of a transaction, but that doesn't fit well with the reality.
This refactoring is also necessary for streaming, where we don't want to wait until the end of the next transaction before replaying the KEEPALIVE messages. That kind of defeat the purpose of a KEEPALIVE message.

Refactor our internal representation for Logical Messages.

---

src/bin/pgcopydb/indexes.c

Even though the create index step must be skipped in some cases (when Postgres doesn't have support for separate CREATE INDEX and ALTER TABLE commands), we should still track the operation as if it was done, which allows the code to later build the constraint with ALTER TABLE syntax. That's when the index gets created actually.
This also allows to then skip the pg_restore entry for both the index and the attached constraint.
Fixes #220

Fix how we skip concurrent build of certain indexes.

---

docs/ref/pgcopydb_list.rst
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_list.h
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb_paths.h
src/bin/pgcopydb/summary.c
src/bin/pgcopydb/summary.h

Implement pgcopydb list progress --summary --json.

---

src/bin/pgcopydb/ld_transform.c

Recent changes had the impact of discarding empty transactions entrirely from the SQL file when transforming them from the JSON file. These transactions act somewhat like a KEEPALIVE message of sorts, as they represent activity in the source database that is not happening in the database we're following.
In this commit we force the transform of these empty transactions to make them part of the SQL file.
Fixes #231

Transform empty transactions from the JSON to the SQL files.

---

tests/unit/setup/7-identity.sql
tests/unit/setup/setup.sql

Add unit testing coverage for "generated as identity" columns.

---

src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/sequences.c

Quote sequence names when checking for privileges.

---

src/bin/pgcopydb/parsing_utils.c

We want to grab the password and remove it from the connection string so that logs don't contain it, and we set the password in the environment of the child processes when running pg_dump etc commands.
Fix the code so that's what actually happens. See #323.

Previous changes broke PG URI password management.

---

CHANGELOG.md
Dockerfile.debian
Dockerfile.debian-qa
GIT-VERSION-GEN
README.md
debian/changelog
docs/conf.py
docs/install.rst
docs/ref/pgcopydb.rst
src/bin/pgcopydb/defaults.h
src/bin/pgcopydb/pgsql.c

Release v0.12.

---

src/bin/pgcopydb/pgsql.c

Only update sentinel.startpos up to flush_lsn.

---

docs/ref/pgcopydb_config.rst

Fix a typo in the filtering docs: include-only-table.

---

src/bin/pgcopydb/summary.c

Attempt to fix a segfault.

---

src/bin/pgcopydb/pgsql.c

Add Postgres backend PID to our SQL (error) logs.

---

src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h

Fix support for DEFERRABLE and INITIALLY DEFERRED constraints.

---

src/bin/pgcopydb/schema.c

Instead of using a static buffer of BUFSIZE for building the SQL string, use the PQExpBuffer API instead here too.

Fix schema_prepare_pgcopydb_table_size to use dynamic memory.

---

src/bin/pgcopydb/pgsql.c

The easy to use API PQexec() and PQexecParams() are blocking, which means those functions could fail to detect when a Postgres connection has been lost, and now wait an indefinite amount of time.
Switch to using the async API PQsendQuery() or PQsendQueryParams() with the PQgetResult() function, all with some lower-level socket API calls such as select(2) and PQconsumeInput() and PQisBusy().
Note that when the server is no longer busy computing the result, we should loop over all the available results... apparently.
Fixes #477

Switch to using libpq async API.

---

README.md

Apologies for such a small edit.
Always leave things better than you found them!

Update README.md (One Typo Fixed)

---

src/bin/pgcopydb/table-data.c
tests/unit/expected/4-parent-data.out
tests/unit/setup/13-parent-data.sql
tests/unit/sql/4-parent-data.sql

- Use COPY with FROM ONLY
Fixes #537

Fix inherit data copy

---

src/bin/pgcopydb/pgsql.c

In some cases, the replay process doesn't reach the endpos due to a problem in the stream process. The problem arises when stream process receives a 'k' message from wal sender and reaches the endpos. But instead of writing the newly received LSN, we write previous LSN with the KEEPALIVE message. The following filtered logs from the streaming process illustrate this issue.
```
endpos is now set to 3/AF01C408
Reported write_lsn 3/AF01C408, flush_lsn 3/AF01BF38, replay_lsn 3/AF01BF38
streamFlush: 3/AF01C408 3/AF01C0A0
Inserted action KEEPALIVE for lsn 3/AF01C0A0 @2023-11-27 11:43:55.946327+0000
Flushed up to 3/AF01C0A0 in file "cdc/0000000100000003000000AF.json.partial"
pgsql_stream_logical: endpos reached on keepalive: 3/AF01C5A0
streamFlush: 3/AF01C5A0 3/AF01C0A0
Inserted action KEEPALIVE …
```

Fix issue where the replay process fails to reach the end position.

---

src/bin/pgcopydb/pgsql.c

Postgres application_name is limited to NAMEDATALEN, sending more bytes than that gives us a NOTICE and we can easily avoid it. In passing, avoid redundancies in the application_name when the ps_buffer already starts with "pgcopydb: ".

Fix application_name truncation notice messages.

---

src/bin/pgcopydb/queue_utils.c

That allows C-c to work in more situations, which is always good.

Fix interrupt handling in queue_receive.

---

src/bin/pgcopydb/cli_copy.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/extensions.c
src/bin/pgcopydb/table-data.c

Blind attempt to fix a segfault in copy extensions code.

---

CONTRIBUTING.md
README.md
docs/install.rst

I used a copy of Citus' CONTRIBUTING.md as a starting point.
I removed sections that are not relevant to pgcopydb, and added some more sections about documentation and running tests.

Introduce CONTRIBUTING.md

---

src/bin/pgcopydb/schema.c

Fix duplicate hazards when listing extension namespaces dependencies.

---

src/bin/pgcopydb/catalog.c

Given ALTER TABLE ... DROP COLUMN ... we could well have a table without an attribute with attnum == 1. Our code used to rely on that to happen in order to allocate our SourceTableAttribute array in-memory, before filling it in.
Instead, use a window-function in the SQL query that we run against our internal SQLite catalogs, using count(*) over(order by attnum) to map whatever the Postgres attnum are into a proper gapless series that starts at one.
Fixes #679.

Review table attributes listing and usage of attnum.

---

src/bin/pgcopydb/schema.c

Extension configuration tables can have foreign key dependencies between them. If the configuration tables are restored in the incorrect order, it can cause foreign key constraint violations.
This change ensures that the configuration tables are ordered according to the dependency order in `pg_constraint`.
I don't expect that this change will be merged as-is, but I've tested it for our use-case and it seems to work.
Fixes #701

Respect FK constraints for extension config tables

---

src/bin/pgcopydb/indexes.c

If the index queue is full, the queue_send() operation gets a EAGAIN error to retry later, and handles the retry policy internally. If this is done while holding the catalog lock, then the create index processes are locked and can't work on emptying the queue: this is a deadlock situation.
To solve it, we need to remove queue_send() from the critical section, and the critical section needs to contain the iteration over the SQLite result set. So first grab the result set in-memory in a new index array construct, and then walk through that array and queue_send() on every item in there.
The index array only contains a single uint32_t value per index, so memory size should not come to be a problem.

Fix a deadlock situation when queueing a table's indexes.

---

src/bin/pgcopydb/cli_copy.c

Solution: Prepare catalog before accessing it!
Fixes https://github.com/dimitri/pgcopydb/issues/729

BUG: summary_start_timing: db is NULL

---

src/bin/pgcopydb/copydb_schema.c

If the user enabled the --estimate-table-sizes option, we should not run ANALYZE queries on the tables that will be split by ctid, as we already ran vacuumdb --analyze-only before.
Sample output from pagila:
```
12:02:38.720 46 INFO   Running vacuumdb --analyze-only on source database before calculating table size estimates
12:02:38.720 46 INFO    /usr/bin/vacuumdb --analyze-only --jobs 4 --dbname 'postgres://pagila@source/pagila?keepalives=1&keepalives_idle=10&keepalives_interval=10&keepalives_count=60'
12:02:38.955 46 INFO   vacuumdb: vacuuming database "pagila"
12:02:39.318 46 INFO   Table public.film_actor is 240 kB large which is larger than --split-tables-larger-than 200 kB, and does not have a unique column of type integer: splitting by CTID
12:02:39.318 46 NOTICE Skipping running …
```

Remove redundant ANALYZE queries

---

src/bin/pgcopydb/pgsql.c

**Deadlock call stack:**
```
%0  0x0000787ac168fe16 in select () from target:/lib/x86_64-linux-gnu/libc.so.6
%1  0x000057db30f718ad in pgsql_sync_pipeline (pgsql=pgsql@entry=0x7ffc8ce1f9c8) at pgsql.c:1979
%2  0x000057db30f5bc2c in stream_apply_file (context=context@entry=0x7ffc8ce1d880) at ld_apply.c:657
%3  0x000057db30f5c495 in stream_apply_catchup (specs=specs@entry=0x7ffc8d030050) at ld_apply.c:112
%4  0x000057db30f549d2 in follow_start_catchup (specs=0x7ffc8d030050) at follow.c:809
%5  0x000057db30f54baa in follow_start_subprocess (specs=specs@entry=0x7ffc8d030050,
%   subprocess=subprocess@entry=0x7ffc8d138da8) at follow.c:860
%6  0x000057db30f55383 in follow_prepare_mode_switch (streamSpecs=streamSpecs@entry=0x7ffc8d030050,
%   previousMode=previousMode@entry=STREAM_MODE_CATCHUP, …
```

Problem: Pipeline sync might deadlock

---

src/bin/pgcopydb/copydb.c

Create a vacuum queue when copying the indexes section too.

Fixes #813: Error when copying indexes

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/file_utils.c
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/pgcmd.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/pidfile.c
src/bin/pgcopydb/string_utils.c

Fixes probable bug sources detected by cppcheck.

Fixes probable bug sources

---

docs/concurrency.rst
docs/features.rst
docs/index.rst
docs/install.rst
docs/intro.rst
docs/resume.rst
docs/tutorial.rst

Some edits regarding fixing typos and expressions for better readability and grammar. Note that Reference Manual section is omitted and shall not be included.

Minor updates to docs

---

src/bin/pgcopydb/cli_ping.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/extensions.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/summary.c
src/bin/pgcopydb/table-data.c

Update COPY statistics during the copy operation.

---

src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_stream.h

* Pass logSQL from spec to context
* Remove unused function argument

Fix bug in passing logSQL from spec to context
