.github/workflows/docker-publish.yml

Hi,
As I'm using your tool and I would like to thank the time gains it brought to me, 
I would like to suggest adding automatic CI/CD for docker image release on GitHub packages.
This PR normally includes latest tag (on main branch push) + semver tags (on tag releases).
The image is also signed through cosign (https://github.com/sigstore/cosign)
It gives the non Debian dockerized version of your tool
```sh
docker pull ghcr.io/blowaxd/pgcopydb:latest
```
To test it
Once merged, it should be available at
```sh
docker pull ghcr.io/dimitri/pgcopydb:{tag}
```
Cheers!

add CICD (Docker + sign) - latest + semver tags

---

docs/ref/pgcopydb_copy-db.rst
docs/ref/pgcopydb_copy.rst
src/bin/pgcopydb/cli_copy.c
src/bin/pgcopydb/cli_copy.h
src/bin/pgcopydb/cli_dump.c
src/bin/pgcopydb/cli_dump.h
src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/cli_restore.h
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/sequences.c
src/bin/pgcopydb/summary.c
src/bin/pgcopydb/table-data.c

This allows to resume from a previous run that would have been interrupted,
or would have failed halfway through. To be able to continue from a previous
run, the user needs to accept a non-consistent operation, where another
snapshot is used the second time.
Internally, the work that has been done already is tracked via lock files
and done files in the working directory.

Implement --restart, --resume --not-consistent.

---

src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/summary.c
src/bin/pgcopydb/summary.h
src/bin/pgcopydb/table-data.c

This is a work-in-progress PR to fix support for constraints for indexes that we can't build concurrently. The ALTER TABLE ... ADD CONSTRAINT ... USING INDEX ... only works for UNIQUE and PRIMARY KEY constraints.
Fixes #22 ; see #23.

Fix support for exclusion constraints.

---

docs/ref/pgcopydb_copy-db.rst
docs/ref/pgcopydb_copy.rst
src/bin/pgcopydb/copydb.c

Refrain from using XDG_RUNTIME_DIR for temp files.

---

Dockerfile.debian-qa
Makefile
src/bin/pgcopydb/cli_copy.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/table-data.c
tests/pagila/docker-compose.yml

The auxiliary process for large objects would somehow piggyback on the main
snapshot connection instance, so make sure it's using its own private
connection.
Since re-using the same connection throughout a COPY process we switched to
multi statements connections, and those need to be closed explicitely. We
missed that in the previous coding.
Using SSL as in debian by default shows more errors, so make sure to run at
least one of our docker compose based testing in SSL too.
Move the copy of sequences data to a proper place that matches the comment
and refactor some function names to distinguish between async behavior (use
_start_ in the name then) and sync behavior. Recent changes made that
distinction hard to follow.

Assorted bug fixes for Postgres connection handling.

---

debian/rules
src/bin/pgcopydb/Makefile
src/bin/pgcopydb/defaults.h

In particular fix the debian package build, and use dpkg-parsechangelog in
that environment so that we report the debian/changelog version string.

Fix version string handling in some cases.

---

docs/ref/pgcopydb_restore.rst
src/bin/pgcopydb/cli_restore.c

Filtering support is important to have to debug the pg_restore archive
catalog editing that pgcopydb implements.

Implement pgcopydb restore parse-list --filters.

---

src/bin/pgcopydb/schema.c

The user in connection must have a superuser role to access the pg_authid
table, which may not be possible for managed services. The fix here is to
use publicly readable view pg_roles
https://www.postgresql.org/docs/current/view-pg-roles.html.

filters: Use pg_roles instead of pg_authid.

---

src/bin/pgcopydb/cli_copy.c
src/bin/pgcopydb/cli_dump.c
src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/pgcmd.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/sequences.c
src/bin/pgcopydb/table-data.c
tests/pagila-multi-steps/copydb.sh

To prevent limitations around lock management when running pgcopydb on a
source database with lots of objects, we now benefit from --not-consistent
as an opportunity to reduce long-running transactions.
It was already the case that --not-consistent wouldn't require exporting or
setting a snapshot, but the opportunity was not yet implemented fully.

Skip long-running transactions when --not-consistent is used.

---

src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/string_utils.c
src/bin/pgcopydb/string_utils.h
src/bin/pgcopydb/table-data.c

Large numbers are hard to read and we don't have that kind of precision anyway.

Fix logging of total reltuples.

---

debian/tests/copydb

The autopkgtest would barf at the existing files left around from the
build-time test.

debian/tests/copydb: Remove directory before starting pgcopydb

---

docs/ref/pgcopydb_create.rst
docs/ref/pgcopydb_stream.rst
src/bin/pgcopydb/cli_common.h
src/bin/pgcopydb/cli_create.c
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/stream.c
src/bin/pgcopydb/stream.h
tests/cdc/copydb.sh

The prefetch command setup the logical decoding operations in a way that
allows transforming each JSON file received into an SQL file. It's a kind of
integration of the `stream receive` and `stream transform` commands,
where the transform process is started in the background as soon as needed.

Implement pgcopydb stream prefetch.

---

docs/ref/pgcopydb_stream.rst
src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/stream.c
src/bin/pgcopydb/stream.h
tests/cdc/000000010000000000000002.sql
tests/cdc/copydb.sh

This command knows how to catch-up from the current tracked position found
at the target database. This position should be created from the LSN
returned by the creation of the logical replication slot, which the other
command `pgcopydb stream setup` already does.

Implement pgcopydb stream catchup.

---

src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/defaults.h
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/stream.c
src/bin/pgcopydb/stream.h
tests/cdc/copydb.sh

Unless when using the --endpos option, the `pgcopydb stream catchup` command
should keep looping and reading the same file again when it's not complete,
allowing concurrent activity with other processes such as `pgcopydb stream
prefetch`.

Review pgcopydb stream catchup command to implement a loop.

---

GIT-VERSION-GEN

This script works very well with development versions but I couldn't yet
figure out how to properly manage released (tagged) version numbers when
building in a docker container. Oops.

Fix GIT-VERSION-GEN default version to 0.8.

---

docs/ref/pgcopydb_clone.rst
docs/ref/pgcopydb_follow.rst
src/bin/pgcopydb/cli_clone_follow.c

- Add coverage for XDG_DATA_HOME in the docs
- Add --split-tables-larger-than in the help string for pgcopydb clone

Improve docs and help strings.

---

docs/ref/pgcopydb_list.rst
src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/table-data.c
tests/pagila/copydb.sh

This allows an external process to list tables, indexes, and sequences that
pgcopydb is processing internally.
Fixes #78

Store the schema elements to a schema.json file.

---

docs/ref/pgcopydb_clone.rst
docs/ref/pgcopydb_copy.rst
docs/ref/pgcopydb_dump.rst
docs/ref/pgcopydb_follow.rst
docs/ref/pgcopydb_list.rst
docs/ref/pgcopydb_restore.rst
docs/ref/pgcopydb_snapshot.rst
docs/ref/pgcopydb_stream.rst
src/bin/lib/log/src/log.c
src/bin/lib/log/src/log.h
src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/cli_create.c
src/bin/pgcopydb/cli_dump.c
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/cli_root.c
src/bin/pgcopydb/cli_sentinel.c
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/main.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pidfile.c
src/bin/pgcopydb/progress.c

Some users are confused by the Unix way of using -vvv to mean “very, very verbose” and accumulate verbosity that way. Introduce --debug as a synonym to -vv and --trace as a synonym to -vvv.
The only drawback to also implement --debug and --trace when we could use --verbose several times is to use yet another short option letter. It seems to be worth it given the user feedback though.
Also introduce a new log level NOTICE between INFO (default verbosity) and DEBUG (extra verbosity) so that we have a new verbose setting that makes sense. The log_notice() macro isn't used much as yet, following patches and PRs will introduce more usage for it.

Implement --debug and --trace, adding to --verbose.

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/ld_apply.c

Specifically, if the clone sub-process fails there is no point for the follow process to continue looping until we're ready to apply the changes, that won't happen. It's best to let know the user that something went wrong, even if that means we stop pre-fetching.

Improve clone --follow sub-process error handling.

---

docs/design.rst
docs/intro.rst
docs/ref/pgcopydb_clone.rst

The concurrency section needed an update to match with the current code, and to cover the pgcopydb clone --follow process tree.
The intro section needed a re-think. Most readers care about how to use pgcopydb and what it does, not so much (yet) about how it's implemented.

Improve docs: intro, design, concurrency.

---

docs/design.rst
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/queue_utils.c
src/bin/pgcopydb/queue_utils.h
src/bin/pgcopydb/stream.c
src/bin/pgcopydb/stream.h
src/bin/pgcopydb/vacuum.c
tests/Makefile

- make sure to reset the FILE * pointer to NULL after closing the file.
- use a stable sub-process to transform JSON files into SQL.
For the second point, we re-use the queuing infrastructure introduced in a recent patch. This allows to have a single sub-process started that will handle all the JSON to SQL transformations during replay.

Bug fixes for the transform process.

---

src/bin/pgcopydb/copydb.c

While a CREATE INDEX command or an ALTER TABLE command is running, at the tcp level we're entirely quiet. When that command runs for more than 2 hours, with the default Linux settings, our connection might get interrupted. Prevent against that.

Also install tcp_keepalives_idle timeout on the target connection.

---

Makefile

The docker build does `make clean install` and we want to keep the version file around in that environment. Have a new `make maintainer-clean` entry to remove the version file.

Refrain from removing the version file in make clean.

---

docs/ref/pgcopydb_stream.rst
src/bin/pgcopydb/cli_sentinel.c
src/bin/pgcopydb/cli_stream.c

This reduces confusion when using the commands, when the previous behaviour would accept any argument on the command line. Also fixes the help strings for pgcopcydb stream sentinet set apply|prefetch command, that doesn't take the <true|false> argument anymore (never did, really).

Enforce argc == 0 for commands without arguments.

---

src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/dump_restore.c

Postgres pg_restore is easily confused with SQL object dependencies when the archive is filtered (either using --section or --use-list, or both). To avoid that problem, issue a DROP TABLE IF EXISTS ... CASCADE; for all the tables we are going to process when --drop-if-exists is in use.
Fixes #126.

Implement our own --drop-if-exists approach.

---

src/bin/pgcopydb/pgsql.c

In this PR, we are checking first if the replication origin on the target exists and then only we drop it . 
This will make the pgcopydb stream cleanup idempotent where earlier it used to throw an error if the replication origin did not exist on the target server for some reason.

Make Drop Replication Origin Idempotent

---

src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_list.h

Providing working directory option to pgcopydb list progress makes it usable for clone & clone follow commands.

Adding dir option pgcopydb list progress command

---

tests/follow-9.6/Dockerfile.pg

The apt.postgresql.org debian repository has archived its support for debian stretch release, in a way that we need to now use
apt-archive.postgresql.org.
We could switch to using a bare debian system as the base for our docker image here, but we would then have to provide and maintain the entry points scripting that the official docker image is providing.

Fix the Dockerfile for wal2json support with older Postgres versions.

---

docs/ref/pgcopydb_list.rst
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_list.h

This allows to manually drop the cache created with --cache option.

Implement pgcopydb list tables --drop-cache.

---

src/bin/pgcopydb/dump_restore.c

It fixes a corner case when --drop-if-exists is used to migrate a database that contains no tables. Before this change, `copydb_target_drop_tables` generates an invalid SQL query `DROP TABLE IF EXISTSCASCADE`.

Fix migration failure of an empty database with --drop-if-exists.

---

src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/cli_create.c
src/bin/pgcopydb/cli_dump.c
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/cli_sentinel.c
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h

Auxilliary commands such as pgcopydb list progress expect the work directory to have been created already. Check that early in the code.

Error out early when work dir does not exists and is expected to.

---

src/bin/pgcopydb/pgsql.c
tests/cdc-endpos-between-transaction/000000010000000000000002.json
tests/cdc-test-decoding/000000010000000000000002.json
tests/cdc-wal2json/000000010000000000000002.json

It fixes an issue under the following conditions,
1. Source doesn't have any activity.
2. `endpos` is set to `current` LSN.
3. The action that crosses the `endpos` is `KEEPALIVE`.
in this case, the written `lsn` that corresponds to `KEEPALIVE` isn't correct, i.e. less than `endpos`. This ultimately leads to Apply process waiting for a statement `>= endpos` which never happens, hence it never terminates.

Fix `lsn` for KEEPALIVE action.

---

src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/table-data.c

For a migration with a huge number of tables, I'm observing large heap memory allocation. In our case, it was 9K tables occupying 11.7 GB heap. This was happening because of,
https://github.com/dimitri/pgcopydb/blob/c2760a02322fc3e73c44a622d6cdb6a3338c1e10/src/bin/pgcopydb/copydb_schema.c#L283-L285
On investigation, I found that it was due to,
```sh
print sizeof(CopyTableDataSpec)
$1 = 1215480
print sizeof(TransactionSnapshot)
$7 = 1210040
print sizeof(LogicalStreamClient)
$8 = 1206768
```
I have changed a few members of `CopyTableDataSpec` to pointers which drastically reduced these allocations.
After this fix,
```sh
print sizeof(CopyTableDataSpec)
$1 = 5440
```

Fix huge memory allocations in copydb_prepare_table_specs.

---

docs/ref/pgcopydb_stream.rst
src/bin/pgcopydb/cli_create.c
src/bin/pgcopydb/cli_sentinel.c
src/bin/pgcopydb/cli_stream.c

Address the failure when `stream cleanup` is used after `clone follow` caused by `dir` is passed as `NULL` to `copydb_init_workdir`, which leads `copydb_prepare_filepaths` to set `topdir` to an undesired location.
Includes cleanup of commands that do not require working directory, by removing `copydb_init_workdir`. And, sets `dir` to appropriate value that do requires working directory.

Fix working-directory issues in stream cleanup and other commands.

---

src/bin/pgcopydb/ld_transform.c
tests/cdc-test-decoding/copydb.sh

Writing directly to the output file opens a window where the file exists and can be read with partial content, either from pgcopydb itself, or from an external tooling. Using a temp filename then switching to the actual expected file protects again partial reads and parse failures.

When transforming into a SQL file, write to a partial file first.

---

src/bin/pgcopydb/file_utils.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h

Writing directly to the target JSON file creates a windows where the file exists and can be read with partial content, either by pgcopydb itself or from external tooling. Using a temp filename then switching to the actual expected file protects again partial reads and parse failures.

When streaming into a JSON file, write to a partial file first.

---

src/bin/pgcopydb/cli_clone_follow.c

The code was ready to be re-used already, but still copy-pasted. In the same file. Well now at least it's cleaner.

Re-use our internal facility followDB().

---

src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/cli_create.c
src/bin/pgcopydb/cli_dump.c
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/copydb_paths.h
tests/pagila-multi-steps/copydb.sh

This allows multiple unrelated subcommands to run at once, each with their own service specific pidfile. Also, most sub-commands do not need a pidfile at all and now can bypass checking for stale pids etc entirely.

Extend the internal notion of auxilliary process to "services".

---

docs/ref/pgcopydb.rst
src/bin/pgcopydb/cli_ping.c
src/bin/pgcopydb/cli_root.c
src/bin/pgcopydb/cli_root.h
tests/blobs/copydb.sh
tests/cdc-endpos-between-transaction/copydb.sh
tests/cdc-low-level/copydb.sh
tests/cdc-test-decoding/copydb.sh
tests/cdc-wal2json/copydb.sh
tests/extensions/copydb.sh
tests/filtering/copydb.sh
tests/follow-9.6/copydb.sh
tests/follow-wal2json/copydb.sh
tests/pagila-multi-steps/copydb.sh
tests/pagila/copydb.sh
tests/unit/copydb.sh

The main use case is in the test-suite where we can use our retry policy to make sure the environment is ready for running the test script. Because it's useful for the project in the context of its unit testing suite, it might be useful also for any project using pgcopydb with some automation around it.

Implement new command: pgcopydb ping

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/cli_copy.c
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/queue_utils.c
src/bin/pgcopydb/queue_utils.h
tests/cdc-endpos-between-transaction/docker-compose.yml

Make the transform process a sibling process to the receive and catchup processes, where it was started by the receive process before. This refactoring simplifies our process management and prepares for being able to transition from the prefetch model to the live replay model.

Refactor the transform process management.

---

src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/file_utils.c
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_replay.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/pidfile.c
tests/cdc-low-level/copydb.sh

The idea is to have an integrated command that does the same as the following unix pipe command:
$ pgcopydb stream receive --to-stdout
| pgcopydb stream transform - -
| pgcopydb stream apply -
The command takes care of setting up the unix pipes and the process tree internally. Makes it easier to use, and the implementation is needed for intagration in the end-user API (pgcopydb clone --follow) anyway.

Implement pgcopydb stream replay.

---

docs/ref/pgcopydb_follow.rst
src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/defaults.h
src/bin/pgcopydb/file_utils.c
src/bin/pgcopydb/file_utils.h
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_replay.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pidfile.c
src/bin/pgcopydb/queue_utils.c
src/bin/pgcopydb/table-data.c
src/bin/pgcopydb/vacuum.c
tests/cdc-endpos-between-transaction/copydb.sh
tests/cdc-test-decoding/copydb.sh
tests/cdc-wal2json/copydb.sh
tests/follow-wal2json/copydb.sh

When pgcopydb clone --follow is used, it is important to prefetch changes while the initial COPY is ongoing, and switch to catchup mode thereafter. That said, when we're all caught-up, we could switch to live replay mode where we have:
stream | transform | replay

Automatically switch from prefetch/catchup to live replay mode.

---

src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/table-data.c

In case of early exit without retries from function copydb_copy_table we would break out of the retry loop and return true, allowing pgcopydb to continue working and report a successful return code to the OS.
In passing, also review error handling in lower-level pg_copy function to prevent trying to COMMIT a transaction in an already failed connection.
Finally, we could have either a client-side connection error or a server-side reported connection error: improve our code to take both the situations into account.
Should fix #201.

Fix internal return value that prevented error handling.

---

docs/ref/pgcopydb_list.rst
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h
tests/unit/setup/4-list-table-split.sql

Otherwise, create a temporary table instead, so that read-only roles can be used on the source database connection to drive the database copy.

Only create pgcopydb schema and table_size table when --cache is used.

---

src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/sequences.c

In case of permission denied, we would break the whole transaction. It might be that only some of the sequences are not accessible for the current user, in which case we want to list them all while SELECT'ing from the ones we are granted access to.

Check that we have sequence privileges before selecting metadata.

---

src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/lock_utils.c
src/bin/pgcopydb/main.c
src/bin/pgcopydb/queue_utils.c
src/bin/pgcopydb/table-data.c

Sytem V resources are created for sub-process communication within pgcopydb run-time. At exit, we need to ensure that we clean-up those resources, which are not automatically reclaimed by the OS.
We used to do that correctly with an atexit(3) handle function for the main logging semaphore, now this is done systematically for all the semaphores and queues created. This also ensures that the same process creates and unlinks the resources, which wasn't always the case in the previous coding.

Ensure clean-up of System V resources.

---

src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/cli_create.c
src/bin/pgcopydb/cli_dump.c
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/cli_sentinel.c
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h

Rather than having to add so many parameters just re-use the options struct as a parameter there.
We still want to have a separate command line option structure rather than use the internal tracking CopyDataSpec structure at command line parsing time, but we can still simplify the code a good deal.
This allows easier adding of new command line options in the future.

Refactor copydb_init_specs to use a CopyDBOptions struct.

---

src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/cli_create.c
src/bin/pgcopydb/cli_dump.c
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/cli_root.c
src/bin/pgcopydb/cli_sentinel.c
src/bin/pgcopydb/cli_stream.c

The --verbose increments the logLevel from “normal” to verbose (or notice), then SQL, then DEBUG, then TRACE. Previous coding would skip the SQL level when incrementing the level, this fixes it.

Fix command line option log level increments (--verbose --notice).

---

src/bin/lib/log/src/log.c

See
https://www.postgresql.org/docs/current/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-JSONLOG for the list of key names that Postgres uses when using jsonlog.

Fix JSON logs key names, use same key names as Postgres.

---

src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h

We need to find sequences that are associated with table columns either as default values (through pg_depend entry between the sequence and pg_attrdef) or as an identity column (through a pg_depend entry between the sequence and the table column directly).
Also, when a sequence is filtered-out from our pg_restore activity, then we need to also filter-out the archive TOC entry for the default value that uses the sequence, in addition to filtering out the table and the sequence themselves.
ALTER TABLE ONLY public.bar ALTER COLUMN id SET DEFAULT nextval(...)
Otherwise we get ERROR: relation does not exist in pg_restore.

Fix Postgres catalog queries that implement sequences filtering.

---

src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/pgcmd.c
src/bin/pgcopydb/pgcmd.h

It could be that the role used to connect to the source and target databases lacks privileges to access some Postgres schema and/or objects within that schema, which means using --exclude-schema on the command line is the right approach.
Fixes #236.

Fix exclude-schema filtering to apply to pg_dump and pg_restore.

---

src/bin/pgcopydb/summary.c
src/bin/pgcopydb/table-data.c

The previous dynamic memory allocation fix was shy of a brick load. See #259.

Fix the previous fix.

---

src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_replay.c
src/bin/pgcopydb/ld_stream.c

Manage the connection internally in the stream_apply_send_sync_sentinel and stream_apply_fetch_sync_sentinel functions, closing the connection each time we have received the result.
Fixes #272

Review and fix connection management for sentinel async updates.

---

src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_replay.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/signals.c
src/bin/pgcopydb/signals.h

When switching replay operating modes we want to replay all the changes that has been streamed locally but have not been caught-up yet. This includes some JSON to SQL transformation work that was missed before.
To be able to receive from the transform queue after having received a signal to stop, we need to also reset the signals control flags, otherwise all we get is an early exit in queue_receive.
Fixes #274

Fix the transition between replay operating modes.

---

src/bin/pgcopydb/copydb.c

We have identified the root cause of the issue where double precision values were going out of range during the COPY operation. It turns out that we were missing the extra_float_digits GUC (grand unified configuration) while copying the float8 data. As a result, when extreme values like '1.7976931348623157E+308' were copied from the source, an overflow occurred leading to the following error:
```log
2023-05-08 14:17:00 16666 ERROR  pgsql.c:2555              TARGET [22003] ERROR:  "1.79769313486232e+308" is out of range for type double precision
2023-05-08 14:17:00 16666 ERROR  pgsql.c:2559              TARGET CONTEXT:  COPY t_numeric_types, line 46650, column c_double_precision: "1.79769313486232e+308"
2023-05-08 14:17:00 16666 ERROR  pgsql.c:2563              TARGET Context: Failed to …
```

Fix double precision out of range during COPY.

---

src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_stream.h

When the previous streaming mode was REPLAY and we attempt to empty the transform queue using `stream_transform_from_queue`, the function waits indefinitely for `QMSG_TYPE_STOP` (or any message) because the queue has already been emptied.

Fix follow_prepare_mode_switch not finishing when previous mode is REPLAY.

---

src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
tests/follow-data-only/Dockerfile
tests/follow-data-only/copydb.sh
tests/follow-data-only/run-background-traffic.sh

Currently we skip applying SQL statements whose source/origin LSN is less than `previousLSN`. When using `pgcopydb clone --follow`, the initial `previousLSN` matches the`consistent_point` obtained during the snapshot.
Comparing LSN of each SQL statement creates a problem when parallel transactions are running during the snapshot capture. These transactions could have statements whose LSN is less than the `previousLSN`. Consequently, the initial portion of some transactions, containing statements with LSN less than the `consistent_point`, are inadvertently omitted.
The fix here is to compare the COMMIT LSN instead of each statement's LSN as it is guaranteed that the COMMIT LSN of every streamed message will be greater than `consistent_point`.
Fixes: #282

Fix issue with missing data from transactions with BEGIN LSN less than consistent_point.

---

src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/queue_utils.c
src/bin/pgcopydb/queue_utils.h

Check the number of messages in the queue before entering a message receive loop that won't exit before reading in the STOP message. When the queue is empty, this turns into an infinite loop.

At follow mode switch, skip empty transform queues.

---

src/bin/pgcopydb/ld_transform.c

During prefetching, when a transaction continues to the next file and the first line of the next file (which is also the only remaining statement of the transaction) is a COMMIT message, it is incorrectly interpreted as an empty transaction. This fix addresses that issue.

transform: Fix transformation to empty txn when first line is COMMIT.

---

src/bin/pgcopydb/ld_apply.c

This fixes the issues where if a txn continues to next file and first statement of that file is not a BEGIN or KEEPALIVE statement then we skip applying COMMIT as well as I/U/T/D leading to the warning "there is already a transaction in progress".
This happens because `reachedStartPos` is set to `false` everytime a new file is processed. Since `reachedStartPos` is never set to true and apply doesn't starts until `BEGIN` or `KEEPALIVE` is found.

Fix apply when file starts with non-begin/keepalive statements.

---

tests/extensions/copydb.sh

This is currently a moving target. Version 3.3.3 adds topology_id_seq as an Extension Configuration Table, and pgcopydb is not ready to handle a sequence there.

Avoid testing with postgis_topology.

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/extensions.c
src/bin/pgcopydb/queue_utils.c
src/bin/pgcopydb/queue_utils.h
src/bin/pgcopydb/table-data.c

Using semaphores for work-sharing isn't ideal and brings some complexity and inefficiencies (each worker process loops over the whole table array). Now that we have introduced Sys V queues, use that mechanism instead to share the workload between table-data COPY workers.
We still need to use a semaphore to create the lockfile and donefile so that we can track progress, resume from interrupted operations, and discover if all the partitions of a single table have been processed already. That said, we don't have to deal with same-table concurrency using the semaphore and files, the queue solves that for us.

Switch from semaphores to message queue to share workload.

---

src/bin/pgcopydb/summary.c
src/bin/pgcopydb/summary.h
src/bin/pgcopydb/table-data.c
src/bin/pgcopydb/vacuum.c
tests/pagila/copydb.sh
tests/unit/copydb.sh
tests/unit/setup/6-multiline-table-name.sql
tests/unit/setup/setup.sql

This ensures that Postgres object names are properly handled even when they may contain multiple lines, which is accepted, possible... and then found in the field.
In passing, ensure that we VACUUM ANALYZE tables without indexes. It's almost relevant to that patch because the failure mode of multiple-lines table names would break our vacuum module.
Fixes #297.

Use JSON format for work-directory summary files.

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/summary.c
src/bin/pgcopydb/table-data.c

- When the filtering results in an empty list of selected tables, make sure we don't enter infinite loop waiting for events that won't happen.
- Make sure to prepare the pgcopydb_table_size (temporary) table when doing the pgcopydb copy ... commands that need it.
- Ensure proper memory allocation and calloc() error detection when printing the summary tables.
- Work around what looks like a compiler bug when int errors = 0; actually sets the errors counter to 32759 on macOs. For that the COPY workers are now always in "fail-fast" mode, we can't count the errors anymore.

Assorted set of small fixes.

---

src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/ld_apply.c

Postgres GUC session_replication_role should be used and set to 'replica' when applying changes from the source database system, to avoid triggers firing again.
Fixes #288.

When applying CDC (logical replication), set role to replica.

---

src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/filtering.c
src/bin/pgcopydb/schema.c
tests/filtering/Dockerfile
tests/filtering/copydb.sh
tests/filtering/exclude.ini
tests/filtering/expected/3-schema-bar-does-not-exists.out
tests/filtering/extra.sql
tests/filtering/include.ini
tests/filtering/sql/3-schema-bar-does-not-exists.sql

Schema queries for dependencies and sequences for exclusion filters where both having bugs, impacting the selection of the objects to be filtered-out when using exclusion filters.
Fixes #280.

Fix schema queries for exclusion filters.

---

src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_stream.h

Currently, we use txnCommitLSN to determine if we have reached the startpos. If the txnCommitLSN is invalid, we read the transaction metadata file from disk or wait until it exists. However, there is a bug that we continue to check the validity of txnCommitLSN and read metadata file even after reaching startpos. This additional work is unnecessary.
Furthermore, this commit partially address an issue where a transaction is split by KEEPALIVE message during the replay phase. Previously, we would wait for transaction metadata file to be created, which would never happen and eventually lead to migration failure.

apply: Remove unnecessary reading for txnCommitLSN after reaching startpos.

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_snapshot.c
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/extensions.c
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_test_decoding.c
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/ld_wal2json.c
src/bin/pgcopydb/progress.c
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h
src/bin/pgcopydb/sequences.c
src/bin/pgcopydb/table-data.c
tests/cdc-endpos-between-transaction/copydb.sh

To finish implementing test_decoding support, we need to be able to look-up attribute names for them being part of a primary-key definition, in order to process UPDATE statements without the old-key: and new-key: parts.
In order to do that we prepare internal data structures to make it easy to provide our internal catalogs representation to the transform sub-processes, both when using the catchup mode API (from disk) or the replay mode API (from a stream).
In passing, share more code in the ld_transform.c module in order to simplify maintenance. It also looks like we're going to use much less memory to implement the same job, that's a nice side effect of this refactoring.

Refactor code to prepare for test_decoding improvements.

---

src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
tests/cdc-endpos-between-transaction/000000010000000000000002.sql
tests/cdc-test-decoding/000000010000000000000002.sql
tests/cdc-wal2json/000000010000000000000002.sql
tests/unit/expected/3-string-escape.out
tests/unit/setup/8-string-escape.sql
tests/unit/setup/setup.sql
tests/unit/sql/3-string-escape.sql

Escape string constants in our SQL files by following the Postgres documentation about String Constants With C-Style Escapes, see:
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS
This format helps guarantee that a single SQL statement in our SQL files are always found on one-line only, which we use in the apply process to avoid having to actually parse the SQL files.
Fixes #336

Fix transform to SQL to escape string values.

---

src/bin/pgcopydb/ld_transform.c

- Fix BYTEA handling: refrain from using C-Style Escapes for BYTEA values.
- Fix LogicalMessageValueEq for INT8OID (typo).
Fixes #338

Assorted transform fixes.

---

src/bin/pgcopydb/copydb.c

The `COPY` statement was timing out because the `statement_timeout` was set to a non-zero value in a migration. Additionally, I quickly checked `pg_dump` to see what other parameters were set for the connection, and I found `lock_timeout`.

Set statement_timeout and lock_timeout to 0.

---

docs/ref/pgcopydb_clone.rst
src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/pg_utils.h
src/bin/pgcopydb/pgcmd.c
src/bin/pgcopydb/pgcmd.h
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h
src/bin/pgcopydb/summary.c
tests/extensions/copydb.sh

When skipping extensions we assume that another process did take care of creating the needed extensions on the target instance, such as e.g. the `pgcopydb copy extensions` command.
The "CREATE EXTENSION" command may create a schema, and we need to skip schemas that such a command would have created on the target already. It is not always possible to track schemas created by extensions, some extension scripts are going out of their way to make sure of that:
DO $$
CREATE SCHEMA tiger_data;
$$;
So we track all the schemas that already exist on the target database and skip creating them when the --skip-extensions command is used.
Fixes #327

Have --skip-extensions also skip pre-existing schemas on the target.

---

src/bin/pgcopydb/ld_transform.c

Also escape backslash character when using E'' notation.

---

src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h

At flushAndSendFeedback time make sure that the current LSN position that we have written is updated as our next startpos. This also makes the startpos available to the other sub-modules (such as transform) at their start-time and when switching between operation modes.
See #331

Ensure startpos is updated when closing stream.

---

src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/parsing_utils.c

When the streaming is interrupted in the middle of a JSON/SQL file and then resumes in replay mode, the transform process needs to read and parse the latest JSON/SQL file in case it's being restarted in the middle of a transaction.
The transform process rewrites the SQL file even when it was done previously, as a way of implementing "cache invalidation" where the source of truth is the JSON file. This PR implements the same approach to the replay mode start-up sequence.
Should fix #331.

Fix resuming the transform process.

---

src/bin/pgcopydb/ld_transform.c
tests/follow-data-only/copydb.sh
tests/follow-data-only/ddl.sql
tests/follow-data-only/dml.sql
tests/follow-data-only/multi-wal-txn.sql
tests/follow-data-only/run-background-traffic.sh

This time we add unit testing to make sure we get it right and avoid regressions.
Fixes #347.

Fix transform escape rules for SQL escape syntax, again.

---

src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/ld_stream.c
tests/cdc-low-level/copydb.sh

When dropping the replication slot on the source database make sure to also remove the snapshot and slot files.
Fixes #293

Fix pgcopydb stream cleanup.

---

src/bin/pgcopydb/cli_ping.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/pgsql.h

The current debian Postgres version string is longer than we anticipated:
"16beta1 (Debian 16~beta1-2.pgdg+~20230605.2256.g3f1aaaa)"
In passing, also make sure that `pgcopydb ping` sets the right GUCs even when using Postgres 9.5, and allow more GUCs for that version too.

Fix our PG_VERSION_STRING_MAX_LENGTH to host more.

---

src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c

When resuming operations from pre-existing files on-disk, we implement some cache invalidation by transforming the JSON file again from scratch, and tracking progress in our internal data structures.
That's needed in case the previous version of the file terminates in the middle of a transaction rather than at a clean transaction boundary.
The previous approach missed that the internal tracking state kept in the StreamContext instance was not shared. Now it is.
See #354.
See #348.
See #331.

Fix stream_transform_resume to share context with stream_transform_file.

---

src/bin/pgcopydb/ld_transform.c

We probably should parse the JSON file as soon as it exists rather than only when a SQL file was already produced in the previous round.
See https://github.com/dimitri/pgcopydb/issues/354.
See https://github.com/dimitri/pgcopydb/pull/348.
See https://github.com/dimitri/pgcopydb/issues/331.
See #355.

Fix stream_transform_resume() cache invalidation of the SQL file.

---

src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_replay.c
src/bin/pgcopydb/ld_stream.h

The return value should be about the success of the operation, not about the fact that the apply mode is enabled or disable: that information is tracked properly in the StreamApplyContext instance given as a parameter.

Fix stream_apply_wait_for_sentinel() return value when interrupted.

---

src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c

It might happen that several JSON messages have the same LSN in our stream, usually that concerns KEEPALIVE and BEGIN and COMMIT message. Unless paying attention to the latest message action, we could skip a BEGIN message that has the same LSN as the latest message even if that message was a KEEPALIVE.
Fix this by keeping around the latest message action. It should be all we need to distinguish a new message from the latest one.
See #354.

Fix skipping streaming messages when resuming from latest JSON file.

---

src/bin/pgcopydb/file_utils.c
src/bin/pgcopydb/file_utils.h
src/bin/pgcopydb/ld_stream.c

Implement a retry loop in case the PIPE buffer is full or something else requires several write attempts before succeeding to write the whole buffer there.

Refactor how ld_stream writes to PIPE stdout.

---

src/bin/pgcopydb/ld_transform.c
tests/cdc-wal2json/000000010000000000000002.sql

That's apparently how to write double-precision integer values without loosing precision.
Should fix #319.

Review double-precision format string from %g to %f.

---

src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/pgsql.c

The list command does not use a --target connection string, so we skip preparing the target catalogs in that case. In passing, also fix a strange way that PQgetisnull() was done for sequences, as the misleading error meant this code got a free round of review.

Fix NULL connection string in: pgcopydb list schema.

---

src/bin/pgcopydb/cli_stream.c

The connection strings are now dynamically allocated but cli_stream somehow didn't get the memo so far.
See #323.
Fixes #360.

The cli_stream module didn't get the pg_strdup() memo for DSNs.

---

docs/ref/pgcopydb_list.rst
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_list.h
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h

The new commands allow listing extension versions in different ways and formats (human-friendly table, JSON):
$ pgcopydb list extensions --available-versions
$ pgcopydb list extensions --requirements
The idea is to prepare for a feature where the extension versions to install on the target database can be provided by the user. To prepare for that, the new commands allow listing available extension versions on the target database and preparing the current requirements file from the extensions available on the target and their default version.

Add facilities to list extension versions.

---

src/bin/pgcopydb/ld_test_decoding.c
tests/follow-data-only/copydb.sh
tests/follow-data-only/ddl.sql
tests/follow-data-only/dml.sql

First, Postgres type names might contain square brackets (arrays), which are used as a delimited in the test_decoding format for typenames. Fix the code to handle the following properly:
f2[text[]]:'{incididunt,ut,labore,et,dolore,magna}'
Then, it turns out that test_decoding emits text in standard SQL form, which is to say in single-quotes and with single-quotes doubled, but with the \n and other characters not-escaped. We need to edit the representation a little so that the ld_transform module processes the text correctly.
Fixes #376

Assorted fixes for the test_decoding parser.

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_apply.c

First, when interrupting the pgcopydb process interactively with C-c while the transform process is running, we should exit the follow loop cleanup.
Second, when using pgcopydb clone --follow --restart we should do a replication setup cleanup first, the same as the pgcopydb stream cleanup command, so that we can actually restart from scratch as the command says.

Fix a couple bugs in pgcopydb clone --follow.

---

src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h

This resolves a problem encountered during the transition from prefetch to replay mode, where the transform process identifies some incomplete transactions. This issue also arises when we interrupt 'follow' and execute a 'follow --resume'.
The root cause is upon resumption of streaming, we may encounter a transaction where the initial messages have LSNs less than the startpos calculated from the latest json file.
The implemented fix involves comparing the LSNs with 'startpos' only when resuming streaming of partially complete transactions. Once 'startpos' is reached, comparison of LSNs for subsequent messages is discontinued.
Fixes: #373

Fix issue with resuming streaming of interleaved transactions.

---

src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h
src/bin/pgcopydb/sequences.c
tests/filtering/copydb.sh
tests/filtering/exclude.ini
tests/filtering/expected/3-schema-bar-does-not-exists.out
tests/filtering/extra.sql

A single sequence could be used by more than one table/column thanks to calling the nextval() function in the default value definition of the column. That said, a sequence is OWNED BY a single table.
In this patch we fix the case where the table that owns the sequence is filtered out from the pgcopydb scope while another table that uses the same sequence is to be copied over... with the sequence, then.
A simple way to create the situation is using the following DDL:
create table app.foo(id bigserial, f1 text);
create table copy.foo(like app.foo including all);
And then filter-out schema app from pgcopydb scope.
Fixes #390.

Fix sequences dependencies tracking.

---

docs/ref/pgcopydb_config.rst
src/bin/pgcopydb/filtering.c
src/bin/pgcopydb/filtering.h
src/bin/pgcopydb/pgcmd.c
src/bin/pgcopydb/pgcmd.h
src/bin/pgcopydb/progress.c
src/bin/pgcopydb/schema.c
tests/filtering/copydb.sh
tests/filtering/include.ini

Despite the name, this filter is an exclusion filter and works exactly the same as the existing "exclude-schema" filter. The new facility is syntactic sugar and allows listing schemas to keep around, which is useful when keeping a single schema and excluding the rest of them.
Fixes #167.
Fixes #218.

Implement the new filter "include-only-schema".

---

docs/conf.py
docs/ref/manual.rst
docs/ref/pgcopydb_compare.rst
src/bin/pgcopydb/cli_compare.c
src/bin/pgcopydb/cli_root.c
src/bin/pgcopydb/cli_root.h
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb_paths.h
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h
tests/pagila/copydb.sh

Implement a set of pgcopydb commands to compare databases, so that it's possible to make sense of a success criteria for the migration. The current implementation is pretty limited and provides a starting point in that direction.

pgcopydb compare schema|data

---

docs/ref/pgcopydb_compare.rst
src/bin/pgcopydb/cli_compare.c
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h

Use an output format that is stable in number of digits and can deal with a bigint overflow (in Postgres a sum(bigint) is numeric): use an MD5 sum and represent it as an UUID.
Also, include the row count in the MD5 computation to better protect against collisions.
Finally, add support for pgcopydb compare data --json.

Improve pgcopydb compare data checksum computation.

---

src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/filtering.c
src/bin/pgcopydb/pgcmd.c
src/bin/pgcopydb/schema.c
tests/filtering/copydb.sh
tests/filtering/exclude.ini
tests/filtering/expected/3-schema-bar-does-not-exists.out
tests/filtering/extra.sql
tests/filtering/include.ini
tests/filtering/sql/3-schema-bar-does-not-exists.sql

First, the parsing of the schema and table names from the INI file was done wrong, in a way that shows with long schema and table names.
Then, I just learned we can't use pg_restore --schema in our context, because it would then skip the CREATE SCHEMA statement and pgcopydb relies on pg_restore to create the schema on the target database.
Fixes #413

Fix filtering on schema names.

---

src/bin/pgcopydb/cli_compare.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h

That way pgcopydb compare data waits for as long as the slowest query that are running concurrently on source and target instances, which is better than serial execution on two different servers.
This changes the JSON format output, because we also now skip fetching the target database catalogs.

Use Postgres async queries to compute checksums.

---

.gitattributes
src/bin/lib/jenkins/Makefile
src/bin/lib/jenkins/README.md
src/bin/lib/jenkins/lookup3.c
src/bin/lib/jenkins/lookup3.h
src/bin/pgcopydb/Makefile
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_test_decoding.c
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/string_utils.c
src/bin/pgcopydb/string_utils.h
tests/cdc-endpos-between-transaction/000000010000000000000002.sql
tests/cdc-low-level/000000010000000000000002.sql
tests/cdc-test-decoding/000000010000000000000002.sql
tests/cdc-test-decoding/copydb.sh
tests/cdc-wal2json/000000010000000000000002.sql

When replaying INSERT/UPDATE/DELETE statements, switch to using PREPARE and
EXECUTE at the protocol level (using the libpq functions PQprepare and
PQexecPrepared). When a statement has already been prepared previously in
our session, we then only send the EXECUTE statement.
This should provide nice performance improvements.
See #414.

Use PREPARE/EXECUTE statements for applying DML in follow mode.

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/signals.c

When a subprocess terminates with a successful return code, it might still have been terminated by a signal, one signal would be SIGSEGV. Arrange our code to report when that happens.
This happened in initialisation of the streaming module when trying to call setvbuf on a un-assigned file descriptor. This is fixed in follow.c when preparing the call.

Fix a SEGFAULT that was hidden by our waitpid() calls.

---

src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb_paths.h
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_replay.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h

This allows a way faster replay because we don't have to wait for Postgres disk sync operation before sending the next SQL command. We need to be careful with what replay_lsn value is sent back to the replication protocol, and for that we need to introduce a tracking between the source LSN and the replay insert LSN.
We still restart applying from the latest LSN that we manage to commit durably using the replication origin API. The advantage of that API is that it's as durable as the transactions replayed on the target system.
See #414.

When applying --follow changes, set synchronous_commit to off.

---

src/bin/pgcopydb/blobs.c
src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/compare.c
src/bin/pgcopydb/extensions.c
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/sequences.c
src/bin/pgcopydb/table-data.c
src/bin/pgcopydb/vacuum.c

This helps understand the process hierarchy better and could be useful to debug or watch long running processes.

Set Process Titles as seen in ps/top/htop etc.

---

src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/parsing_utils.c

To work with shorter timeouts in network stacks (firewall, NAT settings, etc), adjust to TCP keepalive settings to quite short values.

Review the TCP keepalives settings.

---

src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/parsing_utils.c
src/bin/pgcopydb/parsing_utils.h
src/bin/pgcopydb/pgsql.c

Allow overriding at the command-line level, also set the parameters in the connection string so that they're effective even when connecting.

Improve connection string TCP keepalive parameters handling.

---

src/bin/pgcopydb/blobs.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/table-data.c
src/bin/pgcopydb/vacuum.c

When failing to start a sub-process (out-of-memory can be reported when calling the fork() system call), properly handle the error rather than continue trying the migration.
In order to cancel the other sub-processes that were succesfully started we then send a TERM signal to all processes in our process group.
Fixes #458

Fix error handling of fork() calls.

---

src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/compare.c
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/progress.c
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h
src/bin/pgcopydb/sequences.c
src/bin/pgcopydb/table-data.c
tests/unit/copydb.sh
tests/unit/setup/4-list-table-split.sql

Using the Postgres function format with the %I formatter allows our code to bypass any formatting internally when re-using the SQL object names, both in our logs and also in the SQL queries we then emit.
Generalize that approach to attribute names, index names, index table names, index constraint names, and sequences names.
Fixes #463.

Fix SQL identifier quoting, generalize using format %I.

---

src/bin/pgcopydb/cli_restore.c

The following command will now parse the pg_restore --list output file and output to standard out the parsed contents, allowing to check the parser.
pgcopydb restore parse-list pre.list

Add a way to debug parsing a list file.

---

src/bin/pgcopydb/dump_restore.c

fix drop cascade issue

---

src/bin/pgcopydb/pgsql.c

This call should not be blocking in our implementation, because we want to be able to react to network problems or server-side interruptions.

Switch our call to PQgetCopyData to async in pg_copy().

---

src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_list.h
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/extensions.c
src/bin/pgcopydb/filtering.h
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_test_decoding.c
src/bin/pgcopydb/ld_wal2json.c
src/bin/pgcopydb/pg_utils.h
src/bin/pgcopydb/progress.c
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h
src/bin/pgcopydb/summary.h
tests/unit/setup/6-multiline-table-name.sql

Now that we grab the Postgres identifier names already quoted, we need to expand our internal structures memory to handle more bytes: the quotes around the names, and also any double-quote char within the name is going to be doubled by the quoting rules.
Fixes #483

Review static memory size of Postgres identifier names.

---

src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/table-data.c
src/bin/pgcopydb/vacuum.c

In the normal case we want the COPY process to continue with the rest of the tables in the queue, and in the fail-fast case we want to bubble-up the problem as fast as possible for a quick total failure.
The partial failure in the normal case can be resumed with the existing option such as --resume, as long as the snapshot still is held, or when using the option --not-consistent.
Also, ensure that when errors happen mid-flight in the COPY processes we still send the STOP messages in the queues, or signal all the other processes to terminate.
See #477

Improve error handling when COPY fails.

---

src/bin/lib/pg/README.md
src/bin/lib/pg/dumputils.c
src/bin/lib/pg/dumputils.h
src/bin/lib/pg/string_utils.c
src/bin/lib/pg/string_utils.h
src/bin/pgcopydb/Makefile
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h
tests/unit/copydb.sh
tests/unit/setup/10-search-path-index-enum.sql
tests/unit/setup/setup.sql

The Postgres tooling for configuration variable settings that are specific to a database is only activated when pg_restore --create is used, which means that pg_restore is in charge of CREATE DATABASE.
In the context of pgcopydb, we do not want pg_restore to create the target database for us, but we still want to copy over the database specific settings that have been applied with either of the following commands:
ALTER DATABASE SET
ALTER ROLE IN DATABASE SET
To achieve that we need to copy some code from the pg_dump and pg_restore implementation and along with it we also vendor-in some of the Postgres common code (a part of string_utils.c) to avoid link-time issues on different packaging systems.
Fixes #489

Add support for database properties.

---

src/bin/pgcopydb/copydb.h

This change will make sure that pgcopydb can write to the database even if the user has set the default_transaction_read_only GUC.

Ensure transactions are not read only by default

---

src/bin/pgcopydb/file_utils.c

The `read_from_stream` function in pgcopydb was encountering a data loss issue when reading from a source system with transaction bodies containing more than `BUFSIZE(1024)` statements. The problem arose from the statically allocated array of size `BUFSIZE(1024)` used to split lines within the function. When the buffer held more than `BUFSIZE(1024)` lines, it caused subsequent lines to be ignored, resulting in data loss.
To resolve this issue, this commit introduces the following changes:
- We now count the number of lines in the buffer before splitting them.
- Dynamically allocate an array to hold the split lines, based on the line count.
Without the fix, pgcopydb used to abort with the following error message.
```
2023-10-12 12:13:47.381 480684 ERROR  ld_transform.c:963        BUG: …
```

Fix data loss when reading large transaction bodies

---

README.md
docs/design.rst
docs/install.rst
docs/ref/pgcopydb.rst
docs/ref/pgcopydb_copy.rst
docs/ref/pgcopydb_snapshot.rst
src/bin/pgcopydb/cli_copy.c
src/bin/pgcopydb/cli_snapshot.c

Changes include:
- typos
- spacing issues
- inconsistent casing
- using earlier versions instead of the latest in the docs
- not listing all available packages for yum based distros. i.e. missing PG16 packages
- inconsistent naming for processes. I decided on having 1 blob metadata worker + N blob data workers. It is up to discussion if this naming makes sense.

Fix various issues with docs

---

Dockerfile
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_replay.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/pgsql.c
tests/Dockerfile.pagila
tests/cdc-low-level/docker-compose.yml
tests/follow-wal2json/docker-compose.yml

When replaying from file, ensure that the last transaction of a file is commited with synchronous_commit on, allowing better tracking of replication progress.
Also, improve our way to keep track of the previousLSN and log when we reach endpos (KEEPALIVE, COMMIT, ENDPOS) to help get a sense of what's happening.
By setting previousLSN to the proper value even when reaching endpos at a KEEPALIVE message that we skip, we allow the overall system to exit properly in case when there is no activity on the source server.
Fixes #500 
See #427 
See #493

Review logical decoding client tracking of LSNs.

---

src/bin/lib/parson/parson.c
src/bin/lib/parson/parson.h
src/bin/lib/parson/tests.c

Also introduce a change to use snprintf() instead of sprintf() in a couple places, following gcc recommandations.

Update the lib/parson vendored-in library to a new version.

---

src/bin/lib/subcommands.c/commandline.c

As sprintf gets deprecated, update sources to use snprintf.

Fix lib/subcommands.c sprintf usage.

---

src/bin/pgcopydb/follow.c

without this change `pgcopydb follow` would fail with e.g.:
> Failed to parse decoding message for UPDATE on table "public"."tablename" which is not in our catalogs
I suspect this PR fixes issue #350
how I have successfully used it with this change:
```
$ pgcopydb snapshot --follow &
$ pgcopydb clone --no-owner --no-role-passwords --no-acl --no-comments --drop-if-exists --verbose
```
and then (while the `pgcopydb clone` is still running) I ran `pgcopydb follow` in a second shell so it would prefetch the changes

fix decoding in transform subprocess when following

---

src/bin/pgcopydb/defaults.h
src/bin/pgcopydb/parsing_utils.c
src/bin/pgcopydb/pgcmd.c
src/bin/pgcopydb/pgsql.c

when the passwords of source and target differ it will always fail on the first connection attempt because it tries to log in with the password for the other DB:
reproducible test case:
```
$ git switch main && make -s bin
Already on 'main'
Your branch is up to date with 'origin/main'.
$ env|grep PGCOPYDB_
PGCOPYDB_SOURCE_PGURI=postgres://testuser1:testPassword@localhost/testdb1
PGCOPYDB_TARGET_PGURI=postgres://testuser2:testPassword@localhost/testdb2
$ ./src/bin/pgcopydb/pgcopydb clone --restart |& grep connect
$ psql -e postgres://postgres@localhost --command="ALTER ROLE testuser2 PASSWORD 'a_different_password';"
ALTER ROLE testuser2 PASSWORD 'a_different_password';
ALTER ROLE
Time: 12.275 ms
$ export PGCOPYDB_TARGET_PGURI="postgres://testuser2:a_different_password@localhost/testdb2"
$ …
```

fix password handling in safeURI

---

src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c

This commit removes the usage of transaction metadata file. Initially, it was used by the apply process to bypass transactions that were already applied. However, this approach had its challenges. Specifically, in live replay mode, a transaction with numerous statements could fill the UNIX PIPE (an IPC primitive used in replay mode), leading to a potential deadlock. This is because the apply process would be waiting for the transaction metadata file. 
By eliminating the transaction metadata file, the apply process lets the transaction proceed and decides whether to apply or skip it based on the commit LSN during the commit phase.
Fixes https://github.com/dimitri/pgcopydb/issues/493 https://github.com/dimitri/pgcopydb/issues/471

Remove the usage of txn metadata file

---

src/bin/pgcopydb/file_utils.c
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_replay.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c

To avoid infinite looping when endpos has been reached it's important to update our endpos value to the sentinel's one even in the main follow process.
In passing, review some error messages.
Also refrain from stopping early from reading data from a PIPE when a terminating signal is received, we should finish reading as per the comments in the code.

Update pgcopydb sentinel in the main follow process.

---

src/bin/pgcopydb/cli_root.h
src/bin/pgcopydb/defaults.h
src/bin/pgcopydb/main.c
src/bin/pgcopydb/pgcmd.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h

Previously, when a connection timeout occurred with the default connection timeout set to pgconnect_timeout (10 seconds), there were no retries. This was because the total retry timeout (maxT) passed to `pgsql_set_retry_policy` in `pgsql_set_interactive_retry_policy` was also set to pgconnect_timeout, which had already elapsed during the initial connection attempt.
To address this issue, the maxT value has been updated to POSTGRES_PING_RETRY_TIMEOUT. This change also means that maxT cannot be configured by altering PGCONNECT_TIMEOUT. If one wants to configure maxT they can change the values in defaults.h or we can make it configurable through some environment variable in future.
After all this change `pgconnect_timeout` seems redundant so removed it.

Improve and fix connection timeout and total retry timeout.

---

src/bin/pgcopydb/follow.c

We actually only need the possibly new endpos value when a process just terminated, in order to decide what to do. So only fetch the sentinel endpos value when a process just terminated.

Reduce calls to follow_get_sentinel() in the main follow process.

---

src/bin/pgcopydb/blobs.c
src/bin/pgcopydb/compare.c
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/queue_utils.c
src/bin/pgcopydb/table-data.c
src/bin/pgcopydb/vacuum.c

Follow up of https://github.com/dimitri/pgcopydb/pull/533#pullrequestreview-1720295497. Context is sometimes msgrcv acts weird and corrupts the value of other stack allocated variables. Using heap allocated queue message as the workaround until its root cause is known.

Use dynamically allocated QMessage for msgrcv.

---

src/bin/pgcopydb/table-data.c

If `statement_timeout` is set on the target COPY may get interrupted, hence this change.

Set GUCs in the connection for COPY to target.

---

src/bin/pgcopydb/ld_stream.c

Currently, when switching between modes, the follow process cleans up context files, which include details like WAL segment size and timeline. However, we haven't been resetting the in-memory state that decides whether the context should be read from these files. This can lead to the usage of outdated timeline information while retriving the context[1][2][3].
This commit addresses this issue by resetting the in-memory state during context cleanup. This ensures that the system will re-read the context from the files after any cleanup, leading to more accurate and reliable timeline information.
[1] https://github.com/dimitri/pgcopydb/blob/8d305a51f82a83bacac6a3fcce716c9450505e57/src/bin/pgcopydb/ld_transform.c#L201-L212
[2] https://github.com/dimitri/pgcopydb/blob/8d305a51f82a83bacac6a3fcce7 …

Invalidate context state during cleanup

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/cli_ping.c

This is a small PR that aims to fix 2 small issues in the codebase.
1. A comment that has a wrong file name. Possibly a copy paste error.
2. A fatal log message that can misguide users into thinking that connections to target nodes have a problem where as the problem lies in setting some GUCs in connections to source postgres nodes.

Fix some copy paste errors

---

.github/workflows/run-tests.yml
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_transform.c
tests/Makefile
tests/cdc-endpos-between-transaction/000000010000000000000002.json
tests/cdc-endpos-between-transaction/000000010000000000000002.sql
tests/cdc-endpos-between-transaction/copydb.sh
tests/endpos-in-multi-wal-txn/Dockerfile
tests/endpos-in-multi-wal-txn/Dockerfile.pg
tests/endpos-in-multi-wal-txn/Makefile
tests/endpos-in-multi-wal-txn/copydb.sh
tests/endpos-in-multi-wal-txn/ddl.sql
tests/endpos-in-multi-wal-txn/docker-compose.yml
tests/endpos-in-multi-wal-txn/multi-wal-txn.sql

Before this update, exiting the process (either reaching ENDPOS or user-initiated abort like Ctrl-C) could leave us in the midst of an unfinished transaction. Upon resumption, PostgreSQL begins streaming from a consistent point, which might be the start of this incomplete transaction or from an earlier one. Our previous method tried to bypass all earlier messages until hitting the final message of the incomplete transaction, but this approach had its shortcomings, especially when the messages originated from several transactions back.
This commit introduces a more straightforward solution. Now, if the process is aborted and the last transaction is not complete, we'll issue a rollback command for that transaction. This ensures a clean and consistent state for a graceful exit and subsequent …

Rollback incomplete txns on graceful exit

---

docs/ref/pgcopydb_clone.rst
docs/ref/pgcopydb_copy.rst
src/bin/pgcopydb/extensions.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/string_utils.c
src/bin/pgcopydb/string_utils.h
src/bin/pgcopydb/summary.c
src/bin/pgcopydb/summary.h
src/bin/pgcopydb/table-data.c

This patch allows reporting the total number of bytes transferred during
a copy operation. However, it has a limitation that the reported value
is only updated after each table is copied. This is because we do not
update table summary files while the copy is in progress.
Changes include:
- 3 new fields in table summary structures:
- network.bytes: total number of bytes transmitted
- network.bytes-pretty: pretty printed form of network.bytes
- network.transmit-rate: pretty printed bytes transmitted per second
- Some new fields on the `pgcopydb list progress --json --summary`
command:
- steps[].network is a new field that exists for COPY step and has
the following fields:
- bytes: total number of bytes transmitted for all tables
- bytes-pretty: pretty printed form of bytes
- …

Add byte level details to list progress command

---

src/bin/pgcopydb/queue_utils.c

Here is a snippet of man page for msgsnd & msgrcv,
```
int msgsnd(int msqid, const void *msgp, size_t msgsz, int msgflg);
ssize_t msgrcv(int msqid, void *msgp, size_t msgsz, long msgtyp,
int msgflg);
DESCRIPTION
The  msgsnd() and msgrcv() system calls are used to send messages to, and receive messages from, a System V message queue.  The calling process must have write
permission on the message queue in order to send a message, and read permission to receive a message.
The msgp argument is a pointer to a caller-defined structure of the following general form:
struct msgbuf {
long mtype;       /* message type, must be > 0 */
char mtext[1];    /* message data */
};
The mtext field is an array (or other structure) whose size is specified by msgsz, a nonnegative integer value.  Messages of …
```

Fix memory corruption while calling SysV msgsnd & msgrcv

---

src/bin/pgcopydb/blobs.c
tests/blobs/copydb.sh

The issue was that we weren't setting the snapshot for the query that fetches the list of large object ids. This inconsistency led to errors when trying to access large objects that weren't restored on target.
Error:
```
15:30:11 108 ERROR  [SOURCE 85] ERROR:  large object 16390 does not exist
15:30:11 108 ERROR  [SOURCE 85] Context: Failed to open large object 16390
15:30:11 107 ERROR  [SOURCE 83] ERROR:  large object 16392 does not exist
15:30:11 107 ERROR  [SOURCE 83] Context: Failed to open large object 16392
```

Fix copying blobs that are not included in snapshot.

---

.dockerignore
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/table-data.c

Currently for each table we are creating and closing a new connection to
the target. Using a same connection would save us some time and resource,
both at pgcopydb and target side.
Also, seting GUCs only once for a given target connection session would
again save us resources. This would also reduce 8 extra log lines that are
currently produced for each table which otherwise would produce noise if we
have say, 10K tables.
Follow-up: Use the same connection for `INDEX` worker where same connection is even more useful.

Use same connection in table copy worker.

---

src/bin/pgcopydb/defaults.h
src/bin/pgcopydb/pgsql.c

This change makes it easier to identify the connections of pgcopydb in
pg_stat_activity. The process title contains information on the current
operation, and the pid of the process is also included in the
application name. This way we can easily identify the connections of
pgcopydb in pg_stat_activity even if the process title is truncated.
Fixes: https://github.com/dimitri/pgcopydb/issues/431

Set application name to process title and pid

---

docs/ref/pgcopydb_compare.rst
docs/ref/pgcopydb_dump.rst
docs/ref/pgcopydb_snapshot.rst
src/bin/pgcopydb/cli_root.c
src/bin/pgcopydb/cli_root.h
src/bin/pgcopydb/cli_snapshot.c

This pull request addresses minor documentation errors for the following `pgcopydb` commands:
- `pgcopydb snapshot`
- `pgcopydb compare`
- `pgcopydb dump`
Additionally, it capitalizes the first letters of `version` and `help` command descriptions.
Furthermore, it renames `create_snapshot_command` to `snapshot_command` for consistency with the existing naming convention. I'm unsure whether it's valuable to introduce this change in the same PR. Please let me know if you'd like me to revert it or create another PR.

Documentation and Naming Improvements

---

src/bin/pgcopydb/follow.c
src/bin/pgcopydb/ld_replay.c

In the follow process, we create two Unix pipes for bidirectional communication between child processes (prefetch, transform, apply) during replay mode. Each child process closes its unused pipe descriptors upon startup. For example, the prefetch process, which only writes to the transform process, closes the read end of its pipe descriptors immediately.
However, the follow process (parent) itself, which initializes these pipes, does not utilize them for communication. Leaving these pipe descriptors open in the follow process leads to an issue where EOF is not sent, even after the child processes close their ends upon completion. This situation can result in a deadlock, especially when an interruption occurs through Ctrl+C or a SIGTERM signal.
Prior to the fix, the transform process would …

Close pipes created by follow after forking childs

---

src/bin/pgcopydb/ld_apply.c
tests/endpos-in-multi-wal-txn/copydb.sh

This commit addresses and resolves the issue of duplicate key errors when resuming partially executed transactions (continuedTxn) in pgcopydb. We have reintroduced the transaction metadata file, which is essential for identifying the commitLSN of a partial transaction.
Unlike our previous approach, which led to a deadlock between the transform and apply phases, this update brings a more efficient process. Now, the apply phase creates metadata for any partial (continued) transactions during the commit. This metadata is then used to accurately skip the already applied partial transaction if a resume is needed.
This fix is crucial, particularly for tables with unique constraints, where executing the same continued transaction twice previously resulted in duplicate key errors. With this …

Fix duplicate key errors on resuming continued txn

---

src/bin/pgcopydb/blobs.c

We would see “WARNING: transaction already in progress” in the logs.

Fix Postgres connection handling in Large Object related code.

---

src/bin/lib/pg/dumputils.c
tests/unit/copydb.sh
tests/unit/setup/10-search-path-index-enum.sql

**Logs**
`zero-length delimited identifier at or near """" 2023-12-15 09:10:12 86 ERROR  pgsql.c:1949              [TARGET 10202] LINE 1: ALTER ROLE ""abc"" IN DATABASE "def" SET "searc... 2023-12-15 09:10:12 86 ERROR  pgsql.c:1949              [TARGET 10202]                    ^ 2023-12-15 09:10:12 86 ERROR  pgsql.c:19`
**Description**
- remove quotes from the identifier

Fix extra quotes of identifier in ALTER database properties

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/catalog.h
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/schema.c

Catalog queries may return a very large number of rows when the source database contain a very large number of objects (tables, indexes, etc). To best cope with that use Single Row Mode to fetch one row at a time in-memory before inserting it to our internal SQLite catalogs.
See #545 
Fixes #532

Use libpq Single Row Mode when fetching catalogs.

---

src/bin/pgcopydb/cli_dump.c
src/bin/pgcopydb/cli_restore.c

Currently, pgcopydb dump & restore doesn't support skipping extensions or filtering because we don't populate the context with extension details & skip list information.

Support skipping extensions & filtering in pgcopydb dump/restore cli

---

src/bin/pgcopydb/catalog.c

The filter clause is not supported by my local SQLite for some reason, so I needed to use a different approach to count the number of constraints on a table.
This fixes the following error:
```
ERROR  Failed to prepare SQLite statement: select count(1) as indexes, count(1) filter(where c.oid is not null) OVER () as constraints from s_index i left join s_constraint c on c.indexoid = i.oid where tableoid = $1
ERROR  [SQLite] misuse of aggregate: count()
ERROR  Failed to count indexes attached to table dist_tables.t1
ERROR  Failed to copy data for table with oid 17226 and part number 0, see above for details
```
Relevant documentation at https://www.sqlite.org/lang_aggfunc.html says:
> The count(X) function returns a count of the number of times that X is not NULL in a group

sqlite: fix misuse of aggregate: count() errors

---

src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h

We track resources likes semaphore and queue into a global array and deallocate the non freed objects using exit handler. The array tracking these resources uses pointers, which could inadvertently track resource handles allocated from the stack.
Here is a valgrind output,
```
valgrind --trace-children=yes --tool=memcheck --leak-check=no pgcopydb stream cleanup
==428404== Memcheck, a memory error detector
==428404== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==428404== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==428404== Command: pgcopydb stream cleanup
==428404==
08:42:09 428404 INFO   Running pgcopydb version 0.14.1.27.g7b14081 from "/home/ubuntu/dimitri/pgcopydb/src/bin/pgcopydb/pgcopydb"
08:42:13 428404 INFO   A previous run has run …
```

Fix stack pointer access while cleaning up resources on exit

---

src/bin/pgcopydb/main.c

We close the FILE which is used to log into file before calling
the `copydb_cleanup_sysv_resources` which still uses log functions leads
to crash due to invalid FILE* access.
This commit fixes the crash by closing the FILE after calling the
cleanup function.

Fix crash on exit with --debug and PGCOPYDB_LOG_FILENAME

---

src/bin/pgcopydb/cli_clone_follow.c
tests/cdc-endpos-between-transaction/copydb.sh
tests/endpos-in-multi-wal-txn/copydb.sh
tests/follow-data-only/copydb.sh
tests/follow-data-only/ddl.sql
tests/follow-data-only/inject.sh

test_decoding transform relies on source catalog to decode the update message.
Prior to this commit, update while using test_decoding would work only while doing `pgcopydb clone --follow`. This commit enables support for update message decoding while using test_decoding plugin in `pgcopydb follow` too.

Attach source catalog even for follow only mode

---

src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/extensions.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/table-data.c

The code to call TRUNCATE ONLY was only active for tables setup with COPY partitioning (--split-tables-larger-than), and was forced to "false" for the other tables.
The code also evolved in a way that it would build a sub-SELECT query with the table attribute list as the "srcQname" argument to the pgsql.c internal bits for the copy, making it impossible to then re-use that bit in the sql command for the TRUNCATE operation.
To fix, implement a new way to prepare the COPY query bits and pieces so that we can re-use the qualified table name in the TRUNCATE command and also build a full COPY (SELECT a, b, c FROM ONLY t WHERE ...) TO STDOUT; query.
In passing, because of the way we are changing the summary files to use our internal SQLite database instead, also push the TRUNCATE command of …

Review the COPY arguments API to fix TRUNCATE calls.

---

docs/design.rst
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/table-data.c

When the COPY table-data workers fail before the iteration over the list of tables is done, we have a race condition where the COPY supervisor would be busy and is not using waitpid(), thus not reacting to worker process termination.
To solve, limit the responsibilities of the COPY supervisor process even more and create a new process that's responsible for iterating over the table list and sending tables/parts to the queue, etc.

Fix error handling (--fail-fast) for copy workers.

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/catalog.h
src/bin/pgcopydb/compare.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/copydb_paths.h
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/lock_utils.c
src/bin/pgcopydb/lock_utils.h
src/bin/pgcopydb/progress.c
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h
src/bin/pgcopydb/summary.c
src/bin/pgcopydb/summary.h
src/bin/pgcopydb/table-data.c
tests/pagila/copydb.sh
tests/pagila/docker-compose.yml

This allows also to entirely remove the need for semaphores to handle
concurrency between worker processes, using SQLite insert-or-ignore for
concurrency control instead.
Also the idea of TablePaths and IndexPaths elements are gone, with the lock
files and the done files mechanisms.
That said, protect SQLite concurrent write access with a semaphore.
SQLite has not been designed for write-write concurrency, so implement a
critical section in our code so that SQLite only sees a single writer at all
time. It may still see multiple readers though.
Because we have re-entrant queries (an SQLite iterator function may then
choose to run another SQLite query), this commit also adds support for
re-entrant semaphore in a way that doesn't call into semop(2) again when we
already are in the critical …

Remove summary files, use our SQLite database instead.

---

src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/copydb.c
src/bin/pgcopydb/follow.c
src/bin/pgcopydb/signals.c
src/bin/pgcopydb/signals.h

The waitpid() API provides the process return code, which can still be zero when the processed was terminated by a signal such as SIGSEGV. Improve our sub-process supervision with taking that into account as an unexpected error condition.

Fix sub-process "success" condition and error handling.

---

README.md
debian/tests/copydb
docs/ref/pgcopydb.rst
docs/ref/pgcopydb_clone.rst
src/bin/pgcopydb/cli_clone_follow.c
src/bin/pgcopydb/cli_root.c
src/bin/pgcopydb/cli_root.h
src/bin/pgcopydb/copydb.c
tests/cdc-endpos-between-transaction/copydb.sh
tests/cdc-low-level/copydb.sh
tests/cdc-test-decoding/copydb.sh
tests/cdc-wal2json/copydb.sh
tests/endpos-in-multi-wal-txn/copydb.sh
tests/follow-9.6/copydb.sh
tests/follow-wal2json/copydb.sh

The copy-db command was deprecated for a while and will get removed from pgcopydb on next release, please upgrade your scripts and integrations.

Removes copy-db command

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/catalog.h
src/bin/pgcopydb/progress.c

Introduce a new query to count the number of tables and indexes already processed from the summary table, fixing the list progress output for items "done".

Fix pgcopydb list progress command.

---

src/bin/pgcopydb/ld_apply.c

Solution: Use flush LSN from target to find the durable LSN.
To find a durable LSN with async commit, we maintain a list of LSN mapping between source(sourceLSN) and target(insertLSN). New mapping will be inserted into the list on COMMIT or KEEPALIVE message.
While reporting the replay_lsn to sentinel we have to get the flush lsn from target and compare it against the insertLSN from the list to find the sourceLSN.
This has been discussed in https://github.com/dimitri/pgcopydb/pull/608#issuecomment-1875144153

Problem: Incorrect flush LSN from source being used to find durable LSN

---

src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/cli_compare.c
src/bin/pgcopydb/cli_dump.c
src/bin/pgcopydb/cli_list.c
src/bin/pgcopydb/cli_ping.c
src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/cli_root.c
src/bin/pgcopydb/cli_root.h
src/bin/pgcopydb/cli_sentinel.c
src/bin/pgcopydb/cli_snapshot.c
src/bin/pgcopydb/cli_stream.c
src/bin/pgcopydb/main.c

The following issues were fixed:
- some options were not recognized
- some nonexistent options were recognized
- some options with required arguments were not expecting an argument
- some commands did not print help messages when given invalid options
I also removed `root_with_debug` global variable that is identical to root CommandLine.

Fix numerous issues with argument parsing

---

.github/workflows/docker-publish.yml
.github/workflows/run-tests.yml

This pull request updates the version of actions/checkout to v4. This update ensures that the latest version of actions/checkout is used, which may include bug fixes, improvements, or new features.

Update actions/checkout version to v4

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/extensions.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/schema.h

Solution: Populate extension configuration objects along with their type values. Based on the type value, perform either table copy or sequence copy.
At the moment we support only copying extension configuration tables & sequences.
I didn't add test for this PR, because I've to hunt the extension which has sequence as part of the config table. I've manually tested with timescaledb which happens to have few sequences part of the extension config table.
```
pgcopydb list extensions
16:26:50.957 49804 INFO   Running pgcopydb version 0.14.1.58.g1f03537 from "/Users/arajkumar/works/dimitri/pgcopydb/src/bin/pgcopydb/pgcopydb"
16:26:50.969 49804 INFO   Using work dir "/tmp/pgcopydb"
16:26:50.973 49804 INFO   Re-using catalog caches
OID |                      Name |               Schema | …
```

Problem: `pgcopydb copy extension` fails when sequences exists part of ext configuration

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/schema.c

It turns out that when using just "exclude-index" in our filtering the code would be confused as to how to implement that filtering option for listing table and sequence objects from the Postgres catalogs.
Should-fix #575

Fix our exclude-index filtering.

---

src/bin/pgcopydb/cli_common.c
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/filtering.c
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_test_decoding.c
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/progress.c
src/bin/pgcopydb/schema.c

Unfortunately -Wshadow=compatible-local does not seem to be available when using llvm as the compiler. Still, debian builds for Postgres community are producing warnings that we can fix.

Fix gcc warnings found when building on i386.

---

src/bin/pgcopydb/catalog.c

When testing clone on a database with BIGSERIAL sequences containing `last_value`s that don't fit into 32-bit integers, I encountered overflow/wrapping, e.g.:
```
[TARGET 27517] ERROR:  setval: value -1249415229 is out of bounds for sequence "image_cid_seq"
```
Adjusting the sqlite routine used resolved the issue, and the correct value was set on the target database.

Fix large sequence lastValue conversion to 32-bit integer

---

src/bin/pgcopydb/filtering.c
src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_test_decoding.c
src/bin/pgcopydb/ld_transform.c
src/bin/pgcopydb/parsing_utils.c
src/bin/pgcopydb/pgcmd.c
src/bin/pgcopydb/progress.c
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/summary.c

Make sure we don't try and allocate a zero-size memory area, which can lead to "corrupted size vs. prev_size". Review all the calloc() call sites and protect them better when they need to be.
See https://github.com/dimitri/pgcopydb/issues/609

Review zero-byte allocation hasards.

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/catalog.h
src/bin/pgcopydb/cli_copy.c
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/extensions.c
src/bin/pgcopydb/schema.c
tests/unit/setup/14-uuid.sql
tests/unit/setup/setup.sql

The SQLite patch series introduced a bug where we would skip extensions even
when the option --skip-extension is not used.
Also adjust the "pgcopydb copy extensions" to the recent changes where we
use a sub-process under a supervisor to simplify snapshot handling.
Fixes #639

Fix eager extension/collation skipping.

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/catalog.h
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/pgcmd.c

Intentionally this PR contains two independent commits to achieve a single
goal mentioned in the title
1. Use appropriate sqlite PRAGMA commands which significantly improved the
performance. Code comments are self explanatory.
2. Batched writes within one big transaction.
**Results**
For a setup of 13K+ tables below is the time taken by pgcopydb list tables
command excluding the time of running postgres query on source.
WAL => `PRAGMA journal_mode = WAL`
Normal => `PRAGMA synchronous = NORMAL`
Txn => `BEGIN`/`COMMIT`
No optimization | WAL | WAL + Normal | WAL + Normal + Txn | WAL + Txn
-|-|-|-|-
1h 18 mins | 8 mins | 53s | 18s | 18s
So finally decided to go with `journal_mode` as WAL along with one big insert transaction.

Improve sqlite catalog setup performance.

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/copydb_schema.c
tests/cdc-wal2json/copydb.sh

When registering the catalog setup, which includes the same-table concurrency threshold, only consider that value when the table partitions have been populated in the cache already. Otherwise the table partitions are going to be computed again anyway.
Fixes #644

Fix cache invalidation of zero --split-tables-larger-than setup.

---

src/bin/pgcopydb/dump_restore.c

**Logs**
```
2024-01-18 14:10:58 53 ERROR  pgsql.c:1978              [TARGET 1664] ERROR:  syntax error at or near "-"
2024-01-18 14:10:58 53 ERROR  pgsql.c:1989              [TARGET 1664] SQL query: ALTER DATABASE vaibhave-test SET "search_path" TO '$user', 'public';
```

Fix database name identifier in ALTER DATABASE properties using PQescapeIdentifier.

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/progress.c
src/bin/pgcopydb/progress.h
src/bin/pgcopydb/schema.h

Since the move of the summary and process information to the SQLite catalogs, we don't have a progress JSON file on-disk with parts of the setup anymore.
The code needed to be updated to behave correctly without having --table-jobs and --index-jobs information.
Fixes #650

Fix pgcopydb list progress.

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/progress.c

The SQLite refactor meant rewriting all the SourceTableArray loops to use a query result iterator instead. Well there is a place for a SourceTableArray loop still, and that's the pgcopydb list progress thing.

Fix confusion around reporting operations in progress.

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/catalog.h
src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/schema.h
src/bin/pgcopydb/table-data.c

Before embedding SQLite we could not depend on aggregates FILTER clause to be available, and as a result we had to aggregate the attribute list in our own C code. Turns out we had strange bugs around that, that hopefully the very simple SQL query will not have.
Should fix #657
Should fix #634

Compute COPY attribute list using SQL.

---

src/bin/lib/sqlite/Makefile

The CFLAGS for sqlite were being overridden by the default CFLAGS, which caused a portion of the sqlite CFLAGS to be ignored. This commit fixes the ordering of the CFLAGS so that the sqlite CFLAGS are applied after the default CFLAGS.
Particularly, we need to apply the -Wno-implicit-fallthrough flag to sqlite, as it generates a lot of warnings with the default CFLAGS on many systems that use -Wimplicit-fallthrough=3.

Fix ordering of CFLAGS for sqlite

---

src/bin/pgcopydb/cli_snapshot.c

Solution: fflush stdout after printing the snapshot id. By default stdout is buffered and flushed only when the buffer is full.

Problem: Snapshot id printed on stdout doesn't appear on console

---

src/bin/pgcopydb/ld_transform.c
tests/cdc-test-decoding/Dockerfile
tests/cdc-test-decoding/continued-txn.json
tests/cdc-test-decoding/continued-txn.sql
tests/cdc-test-decoding/copydb.sh

Missing xid triggers the following error during apply/replay.
"BUG: parseTxnMetadataFile is called with transaction xid: 0"
Solution: Use xid from commit message as a transaction xid.
Unlike wal2json, test_decoding don't have xid in the DML logical messages. So we use the xid from the COMMIT message to update the transaction xid.

Problem: xid is missing in test_decoding commit for a continued txn

---

src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/schema.h

This function does not exists anymore, but the header was still defined and the call site was not removed yet.
Closes #688
See #684

Cleanup schema_drop_pgcopydb_table_size.

---

src/bin/pgcopydb/defaults.h

pgcopydb recently switched to Boehm-Demers-Weiser Garbage Collector[1] and replaced malloc family with GC_malloc and friends. However, strdup is not replaced to GC_strdup.
Solution: Use macros to replace strdup/strndup with it's GC variant.
[1] https://github.com/dimitri/pgcopydb/pull/647

Problem: Still old variant of strdup has been used

---

src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/summary.c
src/bin/pgcopydb/table-data.c

We use `done_time_epoch` from `timings` to populate `runState`, which helps to skip already processed table sections.
However, we call `summary_start_timing` regardless of whether the section has been already done or not., which causing insertion(insert or replace) of default value to `done_time_epoch` because `summary_start_timing` won't be called for already done section.
Without this fix, while resuming after the interruption pgcopydb would do pre-data restore again leading to table already exists error.
Solution: Check whether the section is already completed using `runState` and exit early without calling `summary_start_timing` for already done section.
Related to https://github.com/dimitri/pgcopydb/issues/692

Problem: Resume after interrupted clone always fails

---

src/bin/pgcopydb/catalog.c

Without this fix the migrations would fail with this error when hit this code path,
```
2024-03-13 09:56:42.303 14231 ERROR  catalog.c:7286            Failed to prepare SQLite statement: select group_concat(attname, ', ' order by attnum)        filter (where not attisgenerated)   from s_attr  where oid = $1
2024-03-13 09:56:42.303 14231 ERROR  catalog.c:7287            [SQLite] near "order": syntax error
```

Fix SQL syntax error in group_concat.

---

src/bin/pgcopydb/Makefile

There were several issues with the CFLAGS in the pgcopydb Makefile. This patch fixes them.
1. Removal of conditional logic for USE_SECURITY_FLAGS
Historically, we needed to support some linux distros such as RHEL6 that did not support the subset of security flags that are required for Microsoft Compliance. However, we are now at a point where we can remove this conditional logic and always use those security flags. This patch removes the conditional logic and always uses the security flags.
2. Fix typo in JENKINS_CFLAGS
The JENKINS_CFLAGS variable was misspelled as CFAGS. This patch fixes the typo.
3. Remove unnecessary override of CFLAGS
The override of CFLAGS was unnecessary and was causing the security flags to be overridden. This patch removes the override. If we do not have -Wformat …

Fix issues with CFLAGS

---

src/bin/pgcopydb/indexes.c
src/bin/pgcopydb/table-data.c

This fixes the case where `copydb_table_data_worker` receives a `QMSG_TYPE_STOP` and we return within the switch statement without calling `catalog_delete_process` outside the switch body. This was causing problems in `list progress`.

Remove table-data worker entry from `process` catalog on finish.

---

src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/pgsql.h

When the replication connection is interrupted due to network or server issues, although there is a retry logic in place, it fails to work effectively. This is because the interruption may leave the last transaction in a partial state, leading to a failure when the ld_transform module attempts to transform the message.
Solution: Add a ROLLBACK message when the last transaction is partially written and the stream is in retry mode.
Use the following query on psql to test the network interruption behaviour while doing DML on source.
```.sql
SELECT pg_cancel_backend(pid) FROM pg_stat_activity where application_name like '%pgcopydb%' and query ilike '%START_REPL%';
\watch 5
```
The following error message will be loged on console when it is interrupted,
> 11:40:54.061 94512 ERROR  unexpected …

Problem: Resume fails after interrupted replication connection

---

src/bin/pgcopydb/ld_apply.c
src/bin/pgcopydb/ld_replay.c
src/bin/pgcopydb/ld_stream.c
src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h

Our existing implementation is basic and it will execute a statement and waits for its result to arrive before issuing next statement. We already improved DML statements targeting same table with in a transaction by coalescing them into [multi-value insert statement](https://github.com/dimitri/pgcopydb/pull/465), but it will be beneficial only for a transaction which has multiple DML statements.
However, we have encountered few cases where the transaction had only one DML statement. This kind of txn will be slower because statements are executed sequentially from the client's perspective and network round trip latency would be added for each statement. For e.g. consider a network round trip of 10ms, executing 100 statements would simply add 1000ms(1s) to the overall response time.
Here is …

Problem: CDC replication/apply is slow

---

src/bin/pgcopydb/pgsql.c

Support pg 11 and 12
Postgres 11 and 12 has not PG_MAJORVERSION_NUM macro,
so this patch replaces it by PG_MAJORVERSION

Support pg 11 and 12

---

src/bin/pgcopydb/table-data.c

Run the following command on a relative large source with quite a few tables with indexes.
```
pgcopydb clone --skip-extension --no-acl --no-owner --table-jobs=1 --index-jobs=1 --notice
```
When you see index creation notice message, interrupt the clone operation using Ctrl + C. You might get log lines like below once interrupted.
```
...
05:46:11.552 3527984 INFO   Skipping sequences, already done on a previous run
05:46:11.557 3527979 NOTICE COPY public.readings
05:46:14.136 3527979 NOTICE COPY public.diagnostics
05:46:14.140 3527983 NOTICE CREATE INDEX IF NOT EXISTS readings_tags_id_time_idx ON public.readings USING btree (tags_id, "time" DESC);
05:46:15.582 3527983 NOTICE CREATE INDEX IF NOT EXISTS readings_time_idx ON public.readings USING btree ("time" DESC);
05:46:15.638 3527979 …
```

Problem: interrupted clone resume fails with index relation already exists error

---

.github/workflows/docker-publish.yml

There are changes in Sigstore's Trusted root used for signing, details are explained here => https://blog.sigstore.dev/tuf-root-update/
Solution: Switch to cosign-release v2.2.3
Fixes https://github.com/dimitri/pgcopydb/issues/723

Problem: Post merge docker push fails

---

src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/table-data.c

Certain configurations on source might not exist in the target server. Before applying the configuration we need to check if it exists.
**before**
```
2024-03-27 18:43:21 64 ERROR pgsql.c:1978 [TARGET 29176] ERROR: unrecognized configuration parameter "sql_inheritance"
2024-03-27 18:43:21 64 ERROR pgsql.c:1989 [TARGET 29176] SQL query: ALTER DATABASE postgres SET "sql_inheritance" TO 'off';
```
**after**
```
12:16:53.589 16592 SQL    pgsql.c:1504              [TARGET 12718] select exists(select name from pg_settings WHERE name = $1);
12:16:53.589 16592 SQL    pgsql.c:1517              [TARGET 12718] 'sql_inheritance'
12:16:53.810 16592 WARN   dump_restore.c:363        Skipping database property sql_inheritance=off which does not exists on the target database
```

Check configuration on target before applying db properties.

---

Dockerfile

We have implemented pipeline mode in
https://github.com/dimitri/pgcopydb/pull/704, but it is not yet enabled by default as the current docker image has PG13.

Bump to Postgres 14 to use libpq pipeline mode

---

src/bin/pgcopydb/ld_stream.c

When we start with an idle source, pgcopydb doesn't send generate keep alive message until it receives message from the source.
pgsql_stream_logical calls [flushFunction](https://github.com/dimitri/pgcopydb/blob/e1dcb60b8f007179536c85a34ab5ce902d932497/src/bin/pgcopydb/pgsql.c#L4294-L4306), however it has been ignored by the implementation because there is [no jsonFile is created yet](https://github.com/dimitri/pgcopydb/blob/e1dcb60b8f007179536c85a34ab5ce902d932497/src/bin/pgcopydb/ld_stream.c#L1406-L1410).
Solution: Don't check for the existence of jsonFile, which leads to generation of keep alive messages causing replay_lsn to move forward.
Related to https://github.com/dimitri/pgcopydb/pull/703.

Problem: replay_lsn is not moving until the first message received

---

Dockerfile

Before, `pg_dump` would refuse to talk to Postgres versions higher than version 14 because it allows only equal or lower major versions. Therefore, we have bumped the Postgres version to 16 to allow `pg_dump` to connect to all available Postgres versions.
@DimCitus [wrote](https://github.com/dimitri/pgcopydb/issues/666#issuecomment-1980917660):
> We could improve the main Dockerfile to use that trick and publish docker images with Postgres 16 by default I suppose.

Dockerfile: make pg_dump more interoperable

---

src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/table-data.c

As BEGIN; TRUNCATE; COPY FREEZE; COMMIT; is an optimisation, we can still proceed with the migration plan when the role used in the pgcopydb clone connection string lacks TRUNCATE privileges on the target table.
Fixes #743.

Check that we have TRUNCATE privileges before running the command.

---

src/bin/pgcopydb/copydb.h
src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/table-data.c

In Postgres pg_dump, the situation of a DROP TABLE happening concurrently to the backup operation is prevented by taking an explicit ACCESS SHARE lock on all the tables early.
This approach is limited to max_locks_per_transaction and can be problematic to operate given large schemas.
In the context of pgcopydb though, we do not need to forbid DROP TABLE happening on the source server while the migration is running, we need to be able to skip a table that has been dropped before we get to COPY it.

Check that a table still exists before running COPY.

---

src/bin/pgcopydb/extensions.c
tests/extensions/copydb.sh

Related to this one: https://github.com/dimitri/pgcopydb/issues/694 and this: https://github.com/dimitri/pgcopydb/pull/717
The `pgcopydb copy extensions` command doesn't create the extension in the original scheme from the source. This patch attempts to fix that by using the `with schema XXX` clause during `create extension`.

Create extensions in the schema of the original extension

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/catalog.h
src/bin/pgcopydb/schema.c
src/bin/pgcopydb/table-data.c
tests/unit/expected/4-list-table-split.out

First, the per-table part count was computed incorrectly, leading to the COPY supervisor adding unknown partitions in the COPY processing queue.
Second, we support both PRIMARY KEYS and also UNIQUE indexes without a NOT NULL constraint, which means we should add a partition for the WHERE IS NULL clause.
Fixes #755 
Fixes #756

Fix COPY partitioning.

---

src/bin/pgcopydb/ld_stream.h
src/bin/pgcopydb/ld_test_decoding.c
src/bin/pgcopydb/ld_wal2json.c
src/bin/pgcopydb/pgsql.c

The utility function pgsql_escape_identifier uses libpq's PQescapeIdentifier which allocates string using C's malloc which requires explicit memory deallocation using PQifreemem. However, we use libgc to auto manage memory with in pgcopydb and we never free the string returned by pgsql_escape_identifier anywhere in the code and causes memory leak.
Solution: Copy the string returned by PQescapeIdentifier into a memory space managed by libgc.

Fix pgsql_escape_identifier memory leak

---

src/bin/pgcopydb/ld_transform.c
tests/cdc-low-level/000000010000000000000002.sql
tests/cdc-test-decoding/000000010000000000000002.sql
tests/cdc-test-decoding/continued-txn.sql

Reverts https://github.com/dimitri/pgcopydb/pull/482
Previously, identifiers coming from the wal2json plugin weren't escaped, and we applied escaping to them while transforming to SQL. However, we recently added proper escaping for all identifiers coming from wal2json [1] using PQescapeIdentifier, which obsoletes the need for escaping in ld_transform.c.
[1] https://github.com/dimitri/pgcopydb/pull/663

Remove redundant identifier escaping from transform

---

src/bin/pgcopydb/ld_apply.c

We used to track last sentinel sync time and update sentinel for every 1 sec. However, the change[1] which adopted sqlite to track sentinel removed the last updated time assignment[2] leading to sentinel write
for every commit message causes replay slowness by almost 6 times.
Solution: Track last sentinel update time
Without the fix, the following snippet will be always executed because `1 < (now - context->sentinelSyncTime)` will be always true!
https://github.com/dimitri/pgcopydb/blob/812a108976b43738ac81dd4fce060851d55076f8/src/bin/pgcopydb/ld_replay.c#L170-L179
[1] https://github.com/dimitri/pgcopydb/pull/601
[2] https://github.com/dimitri/pgcopydb/pull/601/files#diff-481cd5fcd15742c022e2a18916c7a508cc7c7d46c264084daab85200e1b10004L477
```
cat ~/dimitri/bench_new.sql | time pgcopydb …
```

Sentinel is updated for every commit

---

src/bin/pgcopydb/catalog.c
src/bin/pgcopydb/copydb_schema.c
src/bin/pgcopydb/summary.c

More places are bound to concurrent accesses to our SQLite catalogs than before. In particular, because we call `copydb_fetch_schema_and_prepare_specs()` from more places when starting the CDC sub-process tree, this needs to be protected in a critical section.
Fixes #734

Fix SQLite database is locked

---

src/bin/pgcopydb/cli_common.c

On #779 we forgot to add short option -g for skip-db-properties.
See https://github.com/dimitri/pgcopydb/pull/779/files#r1601520982

Add missing args for skip-db-properties option

---

src/bin/pgcopydb/summary.c

This leads to considering `0` as `null` while querying and table with partnum as 0 is never matched.
Also fix typo which refers partnum as partnumber.

Incorrect type used for `partnum` while querying summary table

---

src/bin/pgcopydb/schema.c
tests/pagila/copydb.sh
tests/unit/expected/6-sequences.out
tests/unit/setup/16-sequences.sql
tests/unit/setup/setup.sql
tests/unit/sql/6-sequences.sql

Fixes: https://github.com/dimitri/pgcopydb/issues/777
I put this up as a fix and a regression test for #777. With some changes to the query I've managed to get it discovering identity + normal sequences:
```
create sequence kbgood_id_seq;
create table kbgood (id integer primary key default nextval('kbgood_id_seq'));
create table kbbad (id integer generated always as identity);
-- implies kbbad_id_seq is created
```
```
12:46:12.370 624 INFO   sequences.c:78            Fetching information for 2 sequences
```
```
12:49:30.865 650 SQL    pgsql.c:1572              [TARGET 308053] 'public.kbbad_id_seq', '1', 'false'
12:49:32.412 650 SQL    pgsql.c:1559              [TARGET 308053] select pg_catalog.setval($1::regclass, $2, $3);
12:49:32.412 650 SQL    pgsql.c:1572              [TARGET 308053] …
```

Allow identity based sequences to be found and reset

---

src/bin/pgcopydb/schema.c
tests/filtering/expected/4-exclude-index.out
tests/filtering/include.ini
tests/filtering/sql/4-exclude-index.sql

[exclude-index] works only when there is no other filter present.
Solution: Fix index listing query to consider exclude-index filters on all possible scenarios.

Allow exclude-index filtering when used with other filters.

---

src/bin/pgcopydb/string_utils.c

During development I created a table with 1000 tuples and in the logs I saw that the format is not so easy to read and understand.
... with an estimated total of 1 0 tuples ...
For numbers with 4, 5, or 6 decimal digits, we should pad the number with zeros.

Improve formatting for pretty printed integers

---

src/bin/pgcopydb/defaults.h
src/bin/pgcopydb/pgsql.c
src/bin/pgcopydb/pgsql.h
src/bin/pgcopydb/schema.c

Get the block size from the origin.
The default value of 8192 was used before no matter what the value is on the origin.
By executing `show block_size;` on the origin/source in the new `pgsql_get_block_size` function.

Get the block size from the origin.

---

.github/workflows/run-tests.yml

There is an issue with the current latest version of the checkout action that causes the action to fail with the following error:
```
/usr/bin/docker exec  affa129063e510f8a1c26695901b387829ac4453b272bbf8e36cd1ed60a961aa sh -c "cat /etc/*release | grep ^ID"
Error relocating /__e/node20_alpine/bin/node: secure_getenv: symbol not found
```
To remedy this, we downgrade our checkout action for stylechecker to the
last known working major version.
In passing I also updated one more version to the latest major.

Update versions for checkout github action

---

src/bin/pgcopydb/ld_transform.c

The logic which removes redundant SET for columns who's value is same as in WHERE clause accesses oldValue using newValue index. Both can have varying size items causing out of bound access.
We use the correct index to access the old column name, but incorrect index has been used to access the old column value.
Original PR which avoids redundant SET if value is same as in WHERE: https://github.com/dimitri/pgcopydb/pull/333
Solution: Use old column index to access it's value

Problem: Array out of bounds access during transform

---

src/bin/pgcopydb/cli_restore.c
src/bin/pgcopydb/dump_restore.c
src/bin/pgcopydb/file_utils.c
src/bin/pgcopydb/file_utils.h
src/bin/pgcopydb/pgcmd.c
src/bin/pgcopydb/pgcmd.h

Instead of creating the whole contents of the file in-memory, write it to disk one line at a time, keeping only that line in-memory during the whole operation.
Also arrange to code to only read the pg_restore --list output one line at a time, no context is needed to be able to parse this file format (pg_dump archive Table Of Contents).
Fixes #811 
Replaces and closes #818

Fix out-of-memory issue in creating our pg_restore list file.

---

src/bin/pgcopydb/cli_restore.c

Before this commit, pgcopydb restore parse-list failed with following error.
```
11:44:52.406 233882 ERROR  Failed to attach '/tmp/pgcopydb/schema/source.db' as source
11:44:52.406 233882 ERROR  database source is already in use
```
cli_restore_prepare_specs already prepases catalogs.

Remove redundant catalog db attach while using restore parse-list 

---

.github/workflows/run-tests.yml

This PR fixes our stylechecker tests using the following changes:
- Updated stylechecker image to a new version with updated packages
- Set a fixed version of checkout action
to not get affected by later releases
- Set safe directory for git repository to fix a new set of errors I got during my tests

Use a fixed version for checkout action

---

docs/include/dump-schema.rst
src/bin/pgcopydb/cli_dump.c

Following error will be seen without this fix,
```
10:46:09.943 284145 INFO   Running pgcopydb version 0.0.21.184.g8c85cce from "/home/ubuntu/dimitri/pgcopydb/src/bin/pgcopydb/pgcopydb"
10:46:09.981 284145 INFO   Using work dir "/tmp/pgcopydb"
10:46:09.981 284145 INFO   Restoring database from existing files at "/tmp/pgcopydb"
10:46:09.984 284145 INFO   Current filtering setup is: {"type":"SOURCE_FILTER_TYPE_EXCL","exclude-table-data":[{"schema":"public","name":"metrics_New"}]}
10:46:09.984 284145 INFO   Catalog filtering setup is: {"type":"SOURCE_FILTER_TYPE_NONE"}
10:46:09.984 284145 ERROR  Catalogs at "/tmp/pgcopydb/schema/source.db" have been setup for a different filtering than the current command, see above for details
10:46:09.984 284145 ERROR  Failed to initialize pgcopydb …
```

Adding filtering flag to pgcopydb dump schema

---

src/bin/pgcopydb/catalog.c

We ensure that extension config tables are queried from source tables based on their dependency(foreign key reference order) order in
https://github.com/dimitri/pgcopydb/pull/702, however while reading from sqlite catalog, we query config tables ordered by ext config table's oid which is not correct.
Here is a response of extension catalog query during the problematic scenario,
In the above result, config table named "_timescaledb_catalog.dimension"(oid:17242) has FK reference on "_timescaledb_catalog.hypertable"(oid:1097590370), but when it is ordered by it's oid, "dimension" will be copied first causing FK reference failure,
> TimescaleDB: 2024-07-12 11:10:15 UTC [19612]: [66910f17.4c9c-1] 24456 tsdbadmin@tsdb,app=pgcopydb[3821763] copy extensions [23503] ERROR: insert or update on …

Extension config tables are not copied in dependency order

---

src/bin/pgcopydb/pgcmd.c

Remove redundant NULL pointer checks

---

tests/blobs/Makefile
tests/cdc-endpos-between-transaction/Makefile
tests/cdc-low-level/Makefile
tests/cdc-test-decoding/Makefile
tests/cdc-wal2json/Makefile
tests/endpos-in-multi-wal-txn/Makefile
tests/extensions/Makefile
tests/filtering/Makefile
tests/follow-9.6/Makefile
tests/follow-9.6/inject.sh
tests/follow-data-only/Makefile
tests/follow-data-only/inject.sh
tests/follow-wal2json/Makefile
tests/follow-wal2json/inject.sh
tests/pagila-multi-steps/Makefile
tests/pagila-standby/Dockerfile
tests/pagila-standby/Makefile
tests/pagila/Dockerfile
tests/pagila/Makefile
tests/unit/Dockerfile
tests/unit/Makefile

`docker-compose`` is an external tool written in python and is deprecated for a while. Github actions also removed support for that recently.
docker cli has a plugin named compose that is available as a command of the cli as in `docker compose`.
`docker-compose` and `docker compose` do not have same specifcations and it is not always a trivial task to migrate from one to another. This commit will only change all the references to the `docker-compose` to `docker compose` in our codebase.
Github Actions removed support for `docker-compose` in https://github.com/actions/runner-images/pull/10368
More details available at https://docs.docker.com/compose/intro/history/
Closes: #847

Use compose plugin of docker

---

src/bin/pgcopydb/schema.c
tests/filtering/exclude.ini
tests/filtering/extra.sql
tests/filtering/include/expected/3-schema-bar-does-not-exists.out

We have a bug when migrating some partitioned tables and some partitions are excluded from the migration.
PostgreSQL command `TRUNCATE ONLY` does not support partitioned tables, and following errors happen if the command is used on partitioned tables:
```
ERROR:  cannot truncate only a partitioned table
HINT:  Do not specify the ONLY keyword, or use TRUNCATE ONLY on the partitions directly.
ERROR:  cannot truncate only a partitioned table
SQL query: TRUNCATE ONLY partitioned_tables.sellers
```
Related: #700
Closes: #856

Bugfix: support filtering out only some of the partitions

---

Dockerfile

We do not pin the postgresql-client causing the test failures after PG17 release due to the issue discussed here in the PG mailing list[1].
> I think there are other issues related to b0e96f3119 (Catalog not-null
constraints) - if I dump a v16 server using v17 tools, the backup can't
be restored into the v16 server.  I'm okay ignoring a line or two like
'unrecognized configuration parameter "transaction_timeout", but not
'syntax error at or near "NO"'.
This commit pins the postgresql-client version as per the docker env variable PGVERSION.
[1] https://postgrespro.com/list/thread-id/2693550

Tests are broken after PG17 release
